### ISSUE TITLE
retina %image%

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#1]
%image% should automatically support HiDPI/retina displays.

**Comment by yourhead** [comment]
Currently %image% produces an <img> tag.

Problem:  The de facto mechanism for supporting retina in an <img> tag is to use an image with twice the pixel dimension as the width/height specified in the img tag.  This works, but has the obvious disadvantage of loading an image that is ~4x the number of pixels and probably considerably slower to load.

There is no de facto solution to this problem:
- media queries and css cannot change the src attribute of an img tag
- javascript works but also slows the page load and if JS is disabled the page may not display correctly.
- javascript swapping can also interfere with other scripts that are running and modifying the img tags.

Suggestions welcome!

**Comment by Barzille** [comment]
What about something like this:
http://www.webkit.org/demos/srcset/

**Comment by yourhead** [comment]
pro: no js
con: doesn't work on ff or ie currently

**Comment by barchard** [comment]
Maybe just tag the image with HTML5 data- attributes and leave it to the RW theme developer to implement retina support? E.g., data-2x="path/to/retina/image.png" then they can just (optionally) add retina.js to their theme. I know, less ideal but covers you from the issues you've addressed. I can just imagine the race conditions of JS swapping images.

**Comment by yourhead** [comment]
@barchard -- exporting a second higher resolution image is already possible -- however that doesn't work everywhere and doesn't help the user when they just drop an image on the page.

And, it's probably worth mentioning: there are at least a few techniques that don't require JS (like the srcset) one above.

**Comment by yourhead** [comment]
Done.
When the original image is at least 2x the size of the exported image, %image% will export a second @2x image with exactly double the resolution and add the srcset to the <img> tag.  It will also double the rendered style properties like borders and drop-shadows to match.
