### ISSUE TITLE
jQuery UI

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#121]
Stack that request the javascriptLib = jQuery UI in their plist, and need it to function, fail.

**Comment by yourhead** [comment]
i was not able to duplicate this bug. i suspect i inadvertently solved this bug already. however without any specific detail it's impossible to know.

but since this is not repeatable in any obvious way in alpha 12, i'm going to mark as closed when alpha 12 is released.

if there is more detail about how to make this happen, i can reopen if necessary.

**Comment by doobox** [comment]
I have confirmed this on two separate machines running the latest S3 beta as at time of writing.
My main machine could be likely to produce obscure bugs, as it's chock block with stacks.
But my mac book air only has the 2 test stacks you made installed, and I see the same result.

I think the simplest way to get you to see this bug is:

Open the plist of the image fun stack.
Change the libraries dictionary, change the name from "jQuery" to "jQuery UI"
Do what ever you need to to ensure the stack has reloaded (I restarted RW to be safe).
Now deploy the image fun stack in the alpha theme, with no other stack on the page.
It does not function!
Check the head of the source code, and note no version of jQuery has been loaded at all.

Previewing the page with the stack in it's broken state, while using the "jQuery UI" plist entry, shows nothing at all in console.app

Safari console just shows an error "variable jQuery" can not be found, which is obvious.

**Comment by doobox** [comment]
Also noted, this behaves exactly the same regardless of wether or not I select "load from CDN" in the Stacks pref's window.

**Comment by yourhead** [comment]
OK. I have done exactly as you suggested.  I have added "UI" to the "jQuery" library line. Then previewed the stack.
- The jQueryUI line appears as expected within the content.
- The library loads into the page.
- The library does indeed seems to contain the correct version of jQuery UI.

Below is a screenshot of the results of that experiment.
![jQueryUI loading](https://dl.dropboxusercontent.com/u/433436/skitched-20150612-174841.jpg)
