### ISSUE TITLE
Context Menu (right mouse click) in Stacks library works only in rare cases

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#134]
Go to Stacks library and perform a right mouse click. Sometime this works on the "Text" Stack or on others, but only in rare cases.
alpha 12

**Comment by yourhead** [comment]
can you please add more info.
you say that it rarely "works" but you don't give any specific info about what "works" entails.

do you mean to be enabled?
or when you use the menu something unexpected happens -- if so, can you say what?

**Comment by jrondorf** [comment]
Performing a right mouse click on a Stack Element in the library brings up the context menu with options like "check for update". 
Performing this right mouse click again on the same Stack Element or another afterwards does not bring up the context menu again. Wait some minutes, then the context menu is coming up again on one of the elements.

**Comment by yourhead** [comment]
I cannot duplicate this behavior. I can do right mouse all day and it behaves as expected.

**Comment by jrondorf** [comment]
Maybe a VM problem... Will install the alpha version on a real machine and try to reproduce. Closing until then.
