### ISSUE TITLE
Document Stacks versions that reflect Stacks API version changes

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#144]
Document ie:

Stacks API v1 introduced in Stacks 1.?.?
Stacks API v2 introduced in Stacks 1.?.?
Stacks API v3 introduced in Stacks 2.?.?
etc....................

**Comment by jrondorf** [comment]
+1

**Comment by doobox** [comment]
Do you have a written record of the above? If not I could go through the stacks plugin archive and pull out when all the API versions changed as a favour if you like.

**Comment by yourhead** [comment]
these are not well documented, not easy to find, nor are the ones from 5 years ago very useful to anyone. perhaps just limit it to the last few?

**Comment by doobox** [comment]
I only categorically know one for sure "7" I don't know the release number of api version 6 even.
Re: Me volunteering to pull the api numbers from the archived stacks plugin files, I discovered they do not exist in these plists.

**Comment by yourhead** [comment]
i'm afraid i simply don't have time to do this level of research and documentation -- and the use case of such a thing seems a bit specious to me. if devs really do desire this, then the docs are open source and i would encourage folks to take it upon themselves to add this to those github projects.

if that doesn't materialize (and i bet it won't) then i'll assume there isn't much need for this.

**Comment by jrondorf** [comment]
https://github.com/yourhead/s3/wiki/API-Version-Numbers
