### ISSUE TITLE
custom library groups are allowed to have an empty title

### ISSUE THREAD

**Issue by NimbleHost** [yourhead/s3#149]
Not sure if this is by design, I would expect the default title of "Untitled" to remain in place if a user deletes it, but doesn't replace it with his/her own title.

**Comment by yourhead** [comment]
to clarify:  if the user sets the title to "" (nothing) -- then "Untitled" should come back.
agreed (if that's what you meant).

**Comment by NimbleHost** [comment]
yes, that's what I meant. thanks for reading my mind~ ;-)

**Comment by yourhead** [comment]
keep the bugs coming. these are great!

**Comment by NimbleHost** [comment]
Will do my best. 😁
