### ISSUE TITLE
partial encapsulated stacks do not uniquify instance IDs when exported templated files

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#158]

**Comment by yourhead** [comment]
does not appear to be an issue with assets as they are not made per-instance unique

**Comment by yourhead** [comment]
only an issue with each scoped templates

**Comment by yourhead** [comment]
problem exists in:  exportTemplatesFromNode:

**Comment by bbyrdhouse** [comment]
Isaiah,

I think that this bug should still be open as of the latest version (a17).
The file that now gets created is missing the prefix "stacks_in_"
![partials_](https://cloud.githubusercontent.com/assets/7376298/8411492/cd1999c2-1e49-11e5-8269-c9f284fe65f8.png)

**Comment by yourhead** [comment]
i don't think i could have made any more mistakes in making such a simple change.

thanks for keeping me on track Gary

i think we'll have it nailed down on the next build
