### ISSUE TITLE
Option for templates of type 'file' to respect existing asset folder hierarchy rather than be exported to the "files" folder

### ISSUE THREAD

**Issue by NimbleHost** [yourhead/s3#159]
This might be a big ask:

Currently, a `page` scoped file template will keep the existing filename provided by the developer, but it is placed in the main "files" folder of the page, and removed from its existing location (if it was a file located within a folder defined in the `Info.plist` `assets` array).

I'd like the option to create file templates, but not have those templates be exported in the main "files" folder of the page with a unique ID as the filename. 

Instead, the existing filename and folder hierarchy would be kept in place. Stacks would simply process it to fill in the relevant values on export/publish.

Essentially, I'd like a `page` scoped template file, but one that "stays where it is" in respect to the pre-existing folder hierarchy provided by the developer.

I realize this can cause filename collisions if the stack is added to the page multiple times, but it would be specifically for stacks which only are added to a page once. As such, I'd suggest either:
- That the use of such a scoped template file automatically limits the stack to one instance on the page (probably best), or
- An additional option which would allow developers to specify that a stack can only be added to a page once (I've created a separate issue for this request #160).

**Comment by yourhead** [comment]
it's an interesting idea. and seems valuable. although technically quite challenging. remembering its location and replacing it after template processing. there's a few pieces to that puzzle that i just don't currently have at the moment.

however, it's far from impossible. i'm going to mark this one as someday. if i see an opportunity to add it, i'll take it -- but just but my best guess is that this will have to come after stacks 2.

**Comment by NimbleHost** [comment]
appreciate you considering it. :-)

**Comment by yourhead** [comment]
if i do this ever -- right now is definitely the best time

**Comment by yourhead** [comment]
OK, after taking a bit of time to analyze i think i'm going to let this one drop. It's a large change, has limited application, and there is substantial risk in upsetting existing stacks.
