### ISSUE TITLE
view mode buttons are cropped at the top using resolutions 1440x900 and below

### ISSUE THREAD

**Issue by designdisorder** [yourhead/s3#169]
![viemodes](https://cloud.githubusercontent.com/assets/867820/8147589/b59ab7e6-1272-11e5-9378-6c206fe4e6b9.png)

**Comment by yourhead** [comment]
non-retina:
![skitched-20150614-020102](https://cloud.githubusercontent.com/assets/98634/8147603/3739cd3a-1239-11e5-8a7c-b68381978f5f.jpg)

retina:
![skitched-20150614-020148](https://cloud.githubusercontent.com/assets/98634/8147604/52a3a686-1239-11e5-9700-bdaeb37d62e0.jpg)

If I grab a similar screenshot (this is a retina display if I'm not mistaken) -- my screen looks substantially different for those buttons.

**Comment by designdisorder** [comment]
This is on a Retina Macbook using 1440x900. I am testing here on OS 10.11 though ...

**Comment by yourhead** [comment]
So weird. Your buttons are obviously and substantially different than mine.

![skitched-20150614-020703](https://cloud.githubusercontent.com/assets/98634/8147617/0df08e54-123a-11e5-914e-c2bae34025fc.jpg)

**Comment by yourhead** [comment]
2px shorter and 2px narrower. and the image isn't even close to centered on yours

**Comment by yourhead** [comment]
Since you're using a new Macbook you have to be using 10.10.3 or 10.10.4 right?

**Comment by designdisorder** [comment]
I'll check that on my other Air just in case. Again, keep in mind this is El Cap. Maybe an issue there ...

**Comment by yourhead** [comment]
oooooohhhhhh.   it's 10.11 -- that explains it.

**Comment by yourhead** [comment]
wow. RW works then? that's a surprise actually. when i read the os diffs i didn't install because one of the static linked libs is no longer available. (open ssl).

**Comment by designdisorder** [comment]
Pretty smooth actually. So far no issues other than the glitch ...

**Comment by designdisorder** [comment]
So, eventually Cupertino is fixing that issue anyhow

**Comment by yourhead** [comment]
good to hear.  i think as soon as RW will link in Xcode 7 i'll consider moving.  And yes -- some UI will definitely have to adjust a bit.

my toolbars (and many other things) are meant to be a variant of 10.10 -- that can be replicated in 10.9 without too much work.

**Comment by yourhead** [comment]
i'm going to close this as i think it's likely 10.11 -- and that's a fluid target for a few months i suspect.
