### ISSUE TITLE
add script tags that load prior to stack js

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#17]
with specific requirements that this work for the velocity.js library

**Comment by joeworkman** [comment]
I am not sure how this could not be done with page scoped JS or HTML templates. It really depends on how the theme sets the order of things inside <head>.

**Comment by yourhead** [comment]
I did some testing.  velocity works pretty well with most things, but, like jQuery, it really needs to load before the code that uses it.  that means that it needs to load after jQuery and before the script that has the stacks closures in it.

this bug is basically saying we need a way to add stuff there -- between jQuery and the stack scripts.
