### ISSUE TITLE
allowedType quirk that can allow unexpected result

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#174]
Scenario : Parent stack HTML:

```
%slice -addTypes="com.mydomain.childstack" -allowedTypes="com.mydomain.childstack"%
```

Child stack HTML : (plist says it is a child of above parent stack):

```
<div class="knownWrapper">%image%</div>
```

Expected result :

User should see plus button. (they do)
Pressing button add an image drop zone (they do)
User should should not be allowed to drop any other stack into the parent stack (they can't).
I should now have faith that all my jQuery can find inside the parent stack is a series of images inside my .knownWrapper class.
All good so far!

Actual Result :

While it is not possible for a user to drop an image stack into the parent stack, It is possible for a user to drop images from finder in between the image drop zones of the parent stack.
This leads to unexpected output HTML as the images are then not wrapped by the .knownWrapper class.

**Comment by yourhead** [comment]
also does not limit partials and perhaps other drag types.

**Comment by joeworkman** [comment]
Oh hey! This is a dup of #672

**Comment by yourhead** [comment]
in beta 9:  but if this causes too much incompatibility chaos i may pull it back out. i'd rather have compatibility that perfection here.
