### ISSUE TITLE
Image processing issues in existing S2 projects

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#175]
I made a copy of the Doobox project file then opened and saved in S3.
When browsing through the pages of the project in S3 I noticed images scattered throughout that have been re-proccessed incorrectly.

eg:

![dooboxs3_rw6](https://cloud.githubusercontent.com/assets/1026876/8155041/eb65ae6a-1337-11e5-8d7a-00de9f4750f3.png)

Studying which images have been corrupted seems to reveal that it is only images with drop shadow on transparent backgrounds (in other words semi opaque areas) that have been affected, like the example above.

Images with clean cut edges on transparent backgrounds, are not affected (in other words images that have either fully opaque or fully transparent pixels only), like the below example.

![dooboxs3_rw6](https://cloud.githubusercontent.com/assets/1026876/8155095/a9ec1662-1338-11e5-8567-48f1db0328f2.png)

I will pull an example page out of the project and get it over to you.

**Comment by yourhead** [comment]
i have looked through my image tests. i'm not seeing this type of behavior myself. but some image processing was updated just to use the latest cocoa libs -- so it's possible.

it would be best to send me a file that way i can see the original image and all the settings involved.

if this can be achieved with a plain vanilla image (as apposed to a whole bunch of extra stacks) that will greatly reduce the amount of time i have to spend in finding the bug.

thx

**Comment by doobox** [comment]
Yep, Just creating a much simplified example for you now. I'll need to create and ensure, I can replicate it in this simplified example with just 2 pages and 2 stacks before I send it over. Cheers.

**Comment by doobox** [comment]
I can ont replicate this by creating a new simplified project. I took the pages from the affected project and just knocked out all the clutter for showing you. I created this in S2 then copied, opened and saved in S3. Re-opened in S3 and the images I expected to be affected as they are in my main project file, are not affected. Not sure how to proceed.

![imagetests3-saved_rw6](https://cloud.githubusercontent.com/assets/1026876/8155671/496c7268-133e-11e5-8519-2f63c94104dc.png)

**Comment by doobox** [comment]
Ok.. I made another copy in finder of my main Doobox S2 project file.
I renamed it in finder.
I opened it in S3 by double clicking it in finder.
This time there are no corrupt images to be found anywhere in the project at all.

This means this bug is not able to be replicated easily, but it's going to be one to watch out for.

**Comment by yourhead** [comment]
ok, if you see anything again, let me know
