### ISSUE TITLE
Allow for an inline top level stack, the one that's default on a new stacks page

### ISSUE THREAD

**Issue by designdisorder** [yourhead/s3#176]
Here is the situation: in order to create your own rendering for stacks, S3 allows now so-called inline stacks which don't come with the default rendering based on the standard DIV wrappers that are present since S1. Even though this is possible for custom stacks being developed, there is still at least one default stack on ever new stacks page that can not be set follow the inline behavior. 

The following behavior is suggested: either use a toggle for this default stack to switch off the normal DIV wrappers (which would then be a behavior and UI that's different for the default stack) or implement a implicit logic to set this stack to inline in case all childs of this stack are inline stacks.

It looks like that the second option supports both new S3 inline stacks but also all stacks created with S2 or S1. 

Deeper background: some OSS UI frameworks out there work best or only if the DOM structures created are following certain strict hierarchies. In case those hierarchies are created using stacks, Div wrapper introduced by stacks interfere with those frameworks. Examples frameworks are jQuery Mobile, impress.js, etc. Those frameworks use DIVs as a declarative language to build object hierarchies and they usually break in case of additional wrappers.

**Comment by designdisorder** [comment]
Isaiah, not sure if we wanna mess around with the RW template rendering you've mentioned in our discussion. If omitting the RW template rendering as a feature, there are a couple of things to keep in mind:
- I don't think that this should be a stacks pref as it is project related and should not be globally switched on or off
- this should actually a be a page specific config that can be switched on/off, the same way you can have different templates in RW for certain pages
- I assume that all the nice features we get from RW like template variable replacements are gone then. So what about template variables that are managed by RW like %title%, %toolbar%, etc. would they actually be still replaced by RW?
- in that context, you would have to implement those template variables within stacks, which I don't know if this is possible

Having all of that in mind, I would rather prefer to build my own theme which would go hand in hand with a couple of stacks specifically made for that template. So, I would rather not go into that direction ...

**Comment by yourhead** [comment]
i like the idea in general. and it's easy to do. i ran a test already. but it seems very dangerous.

even in quick tests of a few themes, removing the outer div produced catastrophic results (no clearing div makes some themes behave oddly with floated content).

either implicitly or via a checkbox if a novice user accidentally enables the feature it will create serious problems. worse, the problems may not show up until the user switches themes or previews.

i do think we should work towards this -- but i think we need to solve some of the basic usability problems first -- and that needs more time than i currently have.

**Comment by designdisorder** [comment]
Let me further check if this is really a deal breaker for some of the use cases i have mentioned. There might be other solutions which I haven't tested yet. I'll keep you posted.

**Comment by joeworkman** [comment]
+1

Stacks 3.1 FTW!!!! ;-)

**Comment by yourhead** [comment]
sorry, this still just seems to dangerous to me. those dangers seem to outweigh the benefits.

**Comment by joeworkman** [comment]
There go my dreams of a RW built Foundation site that is indistinguishable from one built by hand. I understand that not everyone would use this responsibly though. #sadpanda

**Comment by yourhead** [comment]
I think there's ways to achieve that end without simply making a user option to disable the top level wrapper.

It's not the idea that I think is bad -- it's that we need a way to make that idea never (or very rarely) result in a bad experience for users.
