### ISSUE TITLE
Image Blur

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#18]
Nice to have: Option to blur images in stacks image editing mode.

Ultimate addition related to image blur : An extra element background image type option "cover", and a slider that appears underneath "blur" if the cover option is chosen.

**Comment by joeworkman** [comment]
I am not really sure that this fits into Stacks. If added, I would assume that the blur would be added to the image itself since doing it via canvas is too complex for a built-in stack. Would adding blur to images be better suited for an app like Pixelmator instead of the Stacks plugin?

**Comment by yourhead** [comment]
i don't see this happening anytime soon.
