### ISSUE TITLE
Possible page scope html issue

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#182]
In the latest alpha14 build, Foundation has broken. I am seeing 2 issues... 
1. The page scoped HTML template that loads the foundation.css file does not seem to be getting loaded onto the page. This is causing all of the Foundation stack to not be properly styled. 
2. In an existing Stacks 2 project, I am getting an exception when previewing. This does not happen when I open in Stacks 2.7.0. 

I have uploaded 2 projects to our Dropbox share. 
1. **Stacks3-NewProject.rw6** is a new project created in S3. 
2. **Stacks2-ExistingProject-PreviewException.rw6** is the existing S2 project that throws the exception on Preview.

**Comment by yourhead** [comment]
please file each item separately. thx

**Comment by yourhead** [comment]
Moved the crash on preview to #194

**Comment by yourhead** [comment]
Moved the page scoped template stuff to #195

**Comment by yourhead** [comment]
Closing this one now that it's split.
