### ISSUE TITLE
API Preview mode not working in RW6 > Project Settings > Master Style.

### ISSUE THREAD

**Issue by tsooj** [yourhead/s3#184]
API Preview mode not working in RW6 > Project Settings > Master Style.

Replicate the case:
- Add a stack to your page using the API preview detection, %[if preview]%Preview Mode%[endif]%
- Switch to the Theme Master Style settings to notice the missing preview information

This is not only related to Stacks v3 but also applies to Stacks v2.

**Comment by jrondorf** [comment]
I confirm that this bug exists...
