### ISSUE TITLE
Support for a Stacks Sidebar Wrapper

### ISSUE THREAD

**Issue by tsooj** [yourhead/s3#186]
It would be great if Stacks is able to add a "Stacks Sidebar Wrapper" into the normal RW Sidebar section.

Clients are requesting for a simple input feature in the settings of a Stacks Element so that they are able to select sidebar as location on the page and the individual Stack is automatically going to take care of that.
Since not every theme is using the same definitions for the used sidebar div it would require one always unique defined div that all Stack devs can use to move the Stacks content into the theme sidebar.

I know that more and more themes support extra content areas but not always within the RW Sidebar location of the theme.
And this new wrapper would also help in the case of people using (older) themes without extra content areas.

Required from the Stacks Plugin:
- Add a Stacks Sidebar Wrapper div into the RW Sidebar, e.g. <div id="stacks_sidebar"></div>

Required from the Stack Element Dev(s):
- Custom logic to move the Stack Element into the Stacks Sidebar Wrapper
- jQuery code example , $("#%id%").appendTo("#stacks_sidebar");

**Comment by yourhead** [comment]
it's an interesting thing -- but it's not clear how the UI would deal with that. i'm afraid this one is probably not going to happen.

**Comment by tsooj** [comment]
The UI is part of each individual Stack Element that would like to use this feature, e.g.
![sidebar](https://cloud.githubusercontent.com/assets/556101/8215533/d752b7f6-1530-11e5-9269-325e1897ed21.jpeg)

All it takes for the Stacks Plugin is to always write that wrapper div into the RW Sidebar.
Hope this helps, let me know if you would like to have an example.

**Comment by designdisorder** [comment]
There are actually a couple of stacks available that basically do the same thing without the wrapper part. I don't see what S3 could improve there. Then you would have to have a drop area that would host stacks that would go into the sidebar. Not sure how that would have to be integrated with the normal content area.
