### ISSUE TITLE
Stack installation error w/o further error tracing in console

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#187]
I just got a "Stack ... could not be installed" issue, most probably because of some file locking in 
~/Library/Containers/com.realmacsoftware.rapidweaver6/Data/Library/Application Support/RapidWeaver/Stacks

There was no helpful information in the console about this, would be nice to have this for further error tracing.

**Comment by yourhead** [comment]
I'm afraid I have nothing to do with that. The installation of all RW addons (including stacks) is handled by the app.  If thee's anything I can do to help, I will, but this one should be filed with RW.
