### ISSUE TITLE
Allow for a custom message inside a %slice%

### ISSUE THREAD

**Issue by designdisorder** [yourhead/s3#190]
Right now this is hard coded to "Drop stacks here." It would be cool to be able to customize that message to reflect more specific requirements like "Drop an Foobar stack here". I guess you get it. In case of an -addTypes being used, this could be rendered left of the plus button telling you actually what's being added by the plus button. What do you think? It's really a UX improvement thing ...

e.g. %slice -label="Drop a Foobar stack here"%

**Comment by jrondorf** [comment]
Reading dynamically the name of the references Stacks (allowedType) would be nice :-)

**Comment by designdisorder** [comment]
Well, in case of one single stack that would be kind of ok, but you can specify more than one and I guess developers should really be able to specifically define the label ...

**Comment by yourhead** [comment]
i feel that the "Drop Stacks Here" is an important part of the stacks identity. i'm afraid i don't see this ever happening. sorry.
