### ISSUE TITLE
uninstall should uninstall all contained stacks as well

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#215]

**Comment by doobox** [comment]
Any way to give the user a warning in certain cases. Ie: We have supplied a set of 3 very visible stacks in the library, but shipped them as one parent and the remaining stacks bundled inside. So the user goes to delete 1 of these stacks, a warning could say "This stack is part of a set, deleting it will delete the entire set of stacks".

**Comment by yourhead** [comment]
something like that.
