### ISSUE TITLE
Longer unit labels get cut off

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#221]
When using longer unit labels, such as: `units` and `rows`, they get cut off in the settings UI. 

Example: http://inft.ly/fAunhvr

**Comment by yourhead** [comment]
i think it can be mended for the slider by fudging the grid a few pixels. but for the number controls with the up/down arrows i think it's a hopeless case -- there's just not that much room there.

it's a tradeoff to get the units out of the edit fields, but i think this is a net win:
con: less room for some units
pro: better experience editing numbers
pro: more space in the number field for the value

**Comment by yourhead** [comment]
the sldier will have about 6 extra pixels in the units field on the next build. enough to get the word "units" in.
