### ISSUE TITLE
Edit UI base font size

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#222]
The base font size for the Edit Mode UI seems to be extremely tiny. I think that its 12px. Can this be changed to be 16px? This is the default size for desktop browsers.

**Comment by yourhead** [comment]
It's unfortunately a function of RW's styled text view.  RW detects font size changes and infers styles from them -- so i'm afraid you have to file this one with Nik.

**Comment by joeworkman** [comment]
So I just added the following CSS to edit mode in order to make it how I wanted it... 

```
%[if edit]%
html,body {
    font-size:16px!important 
}
%[endif]%
```

**Comment by doobox** [comment]
Please no Joe!. Now we'll all have to defend against that when we don't want the larger font size in our elements.

**Comment by joeworkman** [comment]
@doobox This only sets the base font size in edit mode. It will not affect any of your stack styles. In fact, it will make them look closer to what they will in preview mode. 

I have been doing this in my Foundation stacks since day 1. For some reason, with Stacks 3, I had to add the !important.

**Comment by doobox** [comment]
Yes but you'r going to make lots of carefully constructed elements of my UI larger. In some cases it may even overflow to an extra line. I will just have to defend against it.
