### ISSUE TITLE
Idea for rgba color picker

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#224]
I know that the color picker can support rgba color. However, it could be a nice option to have a color + number box for color + opacity. Just a thought... 

In fact, I did not see an opacity slider in the default color picker. Does that have to be enabled?

**Comment by yourhead** [comment]
i like the idea -- but it would be strange that some items (pure stacks UI) would use special color pickers and other items (RW controlled UI) would use the apple color picker.

i think this really needs to be implemented at the app level, not just in a plugin.
