### ISSUE TITLE
Update Site Assets not getting published

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#226]
I had a stack installed as a .devstack. I update a file that was being loaded as a site asset. RapidWeaver never publishes the new file. 

I verified that the file indeed changed inside the .devstack. Even restarting RapidWeaver did not resolve this. The old file was still published. 

The only fix was to change the stack to use a .stack extension.

**Comment by yourhead** [comment]
can you provide any more detail on this. i can't duplicate.

**Comment by joeworkman** [comment]
Well its not doing it today... I guess you can close this. I will reopen if I see it again.

**Comment by yourhead** [comment]
PBKAC
