### ISSUE TITLE
Font Awesome not loading when requested

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#228]
Requesting "Font Awesome" library in the plist is having no effect.
Font Awesome link is not loaded into the head.
Testing in Alpha theme.

![info_plist_and_theme_plist](https://cloud.githubusercontent.com/assets/1026876/8427397/cb432ff8-1f0e-11e5-9d6f-ca3c4b501c1b.png)

**Comment by doobox** [comment]
It appears that the string: "Font Awesome" does not work.
But the string : "FontAwesome" does work.
So it may just be a case of updating the docs as this does not need to be backward compatible.

**Comment by doobox** [comment]
Also just discovered that in the Stacks prefs, loading font awesome form the max cdn works, but loading it from the local file does not work.
It shows the local link in the head, but has no effect on the font awesome html in the page.

![web_inspector_ _index_html](https://cloud.githubusercontent.com/assets/1026876/8434700/d7b2a030-1f44-11e5-834b-a6940e1cdde7.png)

**Comment by yourhead** [comment]
I think "FontAwesome" -- without the space is probably how it should be. i think we'll call this a documentation bug.

but i couldn't find it documented anywhere yet.  (except on my computer)   ;-)

is there a specific page of docs that this came from?

**Comment by doobox** [comment]
Not in the now official API but was referencing from here in the libraries paragraph : https://github.com/yourhead/ImageFunStack

**Comment by yourhead** [comment]
ok. then i change my mind. that's been up for quite a while. i think maybe better to just support both with/without the space.
