### ISSUE TITLE
Font awesome icons do not always display in edit mode

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#229]
As mentioned in the list, but simplified to a default stack example (leaving my stacks out of the equation).

![fullscreen_30_06_2015_17_33](https://cloud.githubusercontent.com/assets/1026876/8436677/02956910-1f52-11e5-984e-ec9b9bbfcb6c.png)

Those are 2 identical HTML stacks, both have "render html" checked.
No font awesome icon is seen in edit mode.

Kuler also reported on the list that he was seeing the icons when he first implemented them, and then all of a sudden he wasn't anymore. So the issue appears intermittent on the face of it, although I have not seen them appear at all here.

**Comment by yourhead** [comment]
i'm certain it happens for you.
but it never happens for me.
if you can help me reproduce it, the bug will get fixed. if you can't...  well...  we've been through this before.  ;-)
