### ISSUE TITLE
min, max arrays in multiple number controls causes crash

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#230]
Not really sure if this is meant to be supported.
Hopefully the attached image is self explanatory.

I can add an array of key "default" but key "min" causes crash.

![info_plist_ _edited](https://cloud.githubusercontent.com/assets/1026876/8474266/cf947faa-20a6-11e5-8eb9-689314c09a7b.png)

**Comment by yourhead** [comment]
From the number control docs:  "Number controls can be used in arrays. Each has its own subtitle and default, all other values are shared."

"all other values are shared"  -- so the min/max should be the same for all the values in that array.  If their min/max/rounding/etc are different then there's a good chance that they're different enough that they shouldn't be in a group together -- and grouping them visually will only cause confusion.
