### ISSUE TITLE
Margin / padding strangeness

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#232]
I don't know what's going on here, but here are the facts.

Was working on a new stack.
I set a top margin on the stack to 100.
Everything looked fine (in preview).
I clicked the pus, beside the default margins control to collapse it again, as I no longer wanted the margin on top.
At this point I recall the redrawing of the screen to be more erratic than usual (but ploughed on).
I then noted that even though I have collapsed the default margin control for the stack, the 100px I added to the top field have now been applied all round the stack (opened, removed 100, and ploughed on).

Now this is where it gets freaky.
At some point later I have gone ahead and re-added the 100 to the default top margin field (we are talking the one stacks provides for every sack).
In edit mode this works as expected.
But in preview mode, no top margin is applied.
I can not replicate this with any other stack.
So I went ahead and doubted my own code, removed all code from the three files that make the stack (html, css, and js). I just put "hello world" into the html file to test.
Low and behold, even without any code in my stack, I can no longer set top margin or indeed top padding???

Re-starting RW makes no difference.
I definitely can't help you see this. Like I say, Removing all code from this stacks files makes no difference, top margin is still not applied to the stack.
All I can Think is this has to be some sort of caching issue, related to the fact I was playing with the default top margin a bit.

![fullscreen_02_07_2015_15_13](https://cloud.githubusercontent.com/assets/1026876/8479374/56d67d9c-20cf-11e5-804e-aa5a3ff783d4.png)

**Comment by yourhead** [comment]
sounds to me like you made a css typo. i don't know why this is here. if you want to report this as a bug, please provide steps for repeating the behavior or some actionable request. thx

**Comment by doobox** [comment]
No typo !
You did not read above :
"I can not replicate this with any other stack.
So I went ahead and doubted my own code, removed all code from the three files that make the stack (html, css, and js). I just put "hello world" into the html file to test.
Low and behold, even without any code in my stack, I can no longer set top margin or indeed top padding???"

Not possible you may think. That's exactly what I thought.

**Comment by yourhead** [comment]
if you provide steps to repeat this, then i will open again. otherwise i will nots. simple as that.
