### ISSUE TITLE
Crash editing existing links in Styled Text

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#248]
1. Add text stack to page. 
2. Add a link to some text. 
3. Exit text edit mode. 
4. Edit text again. 
5. Click on link to edit it. 
6. Crash!

**Comment by yourhead** [comment]
2015-07-05 16:05:38.389 RapidWeaver 6[63071:1202697] [<YHStacksDocument 0x100f376e0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key tree.
2015-07-05 16:05:38.392 RapidWeaver 6[63071:1202697](0   CoreFoundation                      0x00007fff915d403c __exceptionPreprocess + 172
    1   libobjc.A.dylib                     0x00007fff9011e76e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff915d3bd9 -[NSException raise] + 9
    3   Foundation                          0x00007fff9828acc5 -[NSObject%28NSKeyValueCoding%29 valueForUndefinedKey:] + 226
    4   Foundation                          0x00007fff9815fc3b -[NSObject%28NSKeyValueCoding%29 valueForKey:] + 385
    5   RWKit                               0x000000010045ef9f -[RWLinkPanel%28Menus%29 _setupPagesMenu] + 63
    6   RWKit                               0x000000010045e9a1 -[RWLinkPanel%28Menus%29 schemeMenu] + 385
    7   RWKit                               0x000000010045fcc8 -[RWLinkPanel awakeFromNib] + 40
    8   AppKit                              0x00007fff9588e159 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 1276
    9   AppKit                              0x00007fff9586d1c5 loadNib + 384
    10  AppKit                              0x00007fff9586c889 +[NSBundle%28NSNibLoading%29 _loadNibFile:nameTable:options:withZone:ownerBundle:] + 727
    11  AppKit                              0x00007fff95a1bcd7 +[NSBundle%28NSNibLoadingInternal%29 _loadNibFile:externalNameTable:options:withZone:] + 150
    12  AppKit                              0x00007fff95a1ba7d -[NSWindowController loadWindow] + 313
    13  AppKit                              0x00007fff95a16c45 -[NSWindowController window] + 80
    14  RWKit                               0x000000010045ff1b -[RWLinkPanel presentPanelWithLink:parent:] + 315
    15  RWKit                               0x00000001004c024c -[RWTextView clickedOnLink:atIndex:] + 396
    16  AppKit                              0x00007fff95c8a995 -[NSTextView mouseDown:] + 2902
    17  AppKit                              0x00007fff9602fddd -[NSWindow _reallySendEvent:isDelayedEvent:] + 510
    18  AppKit                              0x00007fff9615d2a3 _NSGestureRecognizerUpdate + 2548
    19  CoreFoundation                      0x00007fff914f0127 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    20  CoreFoundation                      0x00007fff914f0080 __CFRunLoopDoObservers + 368
    21  CoreFoundation                      0x00007fff914e22ba __CFRunLoopRun + 1178
    22  CoreFoundation                      0x00007fff914e1bd8 CFRunLoopRunSpecific + 296
    23  HIToolbox                           0x00007fff8f83756f RunCurrentEventLoopInMode + 235
    24  HIToolbox                           0x00007fff8f8372ea ReceiveNextEventCommon + 431
    25  HIToolbox                           0x00007fff8f83712b _BlockUntilNextEventMatchingListInModeWithFilter + 71
    26  AppKit                              0x00007fff958f398b _DPSNextEvent + 978
    27  AppKit                              0x00007fff958f2f38 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
    28  AppKit                              0x00007fff958e8bd3 -[NSApplication run] + 594
    29  AppKit                              0x00007fff95865324 NSApplicationMain + 1832
    30  libdyld.dylib                       0x00007fff8cf575c9 start + 1
    31  ???                                 0x0000000000000001 0x0 + 1)
