### ISSUE TITLE
trueValue / falseValue dictionaries for array controls

### ISSUE THREAD

**Issue by atavernor** [yourhead/s3#251]
It would be great to have an array of corresponding trueValue's and falseValue's for array controls. 

This would greatly reduce the amount of expensive logical if statements involved when, for example, inserting class names in to a div within an html template based upon the selection state of button or checkbox arrays. 

In practice, this would mean instead of writing:
`<div class="%[if %id=button[0]%]% myClass1 %[endif]% %[if %id=button[1]%]% myClass2 %[endif]%">`

we could simply write:
`<div class="%id=button[0]% %id=button[1]%">`

where "myClass1" and "myClass2" are string definitions in the trueValue dictionary, as would be the case with non array based controls.

**Comment by yourhead** [comment]
yes, i think this makes sense.  unfortunately this is a substantial change -- i don't think i'll be able to sneak it in before S3 release. but we'll shoot for 3.1.

**Comment by joeworkman** [comment]
It would also be awesome if I added `%id=button%` then it would simply add every value from that array. Maybe have a delimiter option so that we can chose that they would be space, comma, etc.

**Comment by joeworkman** [comment]
If there was a `top-of-the-list` label in github, this should get it. :-)

**Comment by joeworkman** [comment]
+1,000,000,000,000

So wish that we caught this one sooner. :"-(

**Comment by joeworkman** [comment]
So how many margaritas and red bulls to label this as a bug? ;-)

**Comment by atavernor** [comment]
I would personally import a case of Italian grappa for you as well :)

**Comment by joeworkman** [comment]
Did this make v3.1?

**Comment by yourhead** [comment]
ok, i have a tentative implementation for this...   however it makes some fundamental changes to value logic -- so i'm a bit nervous.

if there are issues discovered i'm going to reserve the right to pull this out at the last minute.
