### ISSUE TITLE
Behaviour of Links Control

### ISSUE THREAD

**Issue by atavernor** [yourhead/s3#253]
Once a link is set the 'Set Link' button now becomes a 'Clear' button.

This means the user no longer has the ability to make a small change to a previously entered URL, the only option is to fully re-type it.

When using warehouse image links and the like, it is not uncommon for users to make a small error in the URL and want to go back and correct it. This is no longer possible. It also precludes the ability to open a previously opened link and copy it, for subsequent pasting into another control.

Users I are quite used to re-opening the link dialog and deleting its contents and this seems a preferable trade off compared to having to re-type long url's for the sake of a one character change.

**Comment by yourhead** [comment]
You may have to duke it out with the group of devs that have been pestering me to change this behavior for the past couple years.  ;-)

**Comment by yourhead** [comment]
maybe there's some way to do both?  have it be clearable and updatable?

**Comment by atavernor** [comment]
Both would be ideal.

It is the users, that I think will complain about this one if it not updatable, that was my only reason for flagging it up. I obviously never mis-type a url :)

**Comment by joeworkman** [comment]
Wow. How did I miss that debate? I have to agree with @atavernor on this one. I don't care for the new behavior. I prefer the old behavior to this.

**Comment by joeworkman** [comment]
The user could lose a bit of work here if they took the time to add classes and other attributes.

**Comment by ghost** [comment]
+1 on this issue.

**Comment by ghost** [comment]
I know I just mentioned this is the Slack Channel but its annoying enough to mention it here too (again)
Please please please bring back the ability edit links.
I've just tried to copy a link that I don't have written down "why would I write it down, I can copy it from another project".....but I cant can I?...aghhhh
