### ISSUE TITLE
devstack reload crash

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#258]
I changed a few files in my stack and went back to stacks and it seemed to crash while it was reloading things. 

Here are the crash report and exceptions: https://infinit.io/_/37GBqxf

**Comment by yourhead** [comment]
weird crash report. don't see anything the matter with that (other than the crash of course) -- is it repeatable?

**Comment by joeworkman** [comment]
not repeatable so far... been working well since

**Comment by yourhead** [comment]
ok, let's just give it a bit and see if it pops up again.
unfortunately that is a crazy ass crash report...   not quite enough to go on -- and not in a user-facing bit of code -- so less urgent.

**Comment by yourhead** [comment]
no new info. closing unless this one pops up again
