### ISSUE TITLE
Feature Request - Stack Folders

### ISSUE THREAD

**Issue by zeebe** [yourhead/s3#267]
A couple of requests for S3 upcoming update. Love that you can make stack folders, but here are a couple of ideas.
1. Make the folders moveable so users can interchange their location.
2. I can see people wanting a lot folders depending on their project, would be nice to be able to save these folders and then choose the ones you want to show.
3. Folder names (I know might be very difficult with length of name).

**Comment by yourhead** [comment]
never put more than one item in a bug/feature -- you can only track their progress if each is individual.

i'll separate these into their own fet-req and close this one. thx.

**Comment by yourhead** [comment]
item 1 is now #267
item 2 is now #268

item 3:  control click on the group icon to rename the group (or click on the name at the top of the library sidebar/window)
