### ISSUE TITLE
Template variable for stack class

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#274]
It would be nice to have a template variable that resolved to the class that is added to the stack. This may already exist?

Ex: com_joeworkman_stacks_cool_stack

**Comment by yourhead** [comment]
i can add it, but it's a low priority. you can guess that value easy enough. it's just the bundle id (with "_" replacing ".") and _stack tacked on the end.

**Comment by joeworkman** [comment]
I know that I can guess it easy enough. But could make development a tad quicker if I don't need to recall the bundleIdD. I was thinking %class% to match the %id%. Surprised that I did not think of this until today.

**Comment by joeworkman** [comment]
Totally closed that by accident...

**Comment by yourhead** [comment]
in beta 9

docs should appear hear shortly:  http://api.yourhead.com/templates/stackClass/
