### ISSUE TITLE
Appcast Update Notes for Single Stack updates

### ISSUE THREAD

**Issue by bbyrdhouse** [yourhead/s3#275]
Add a way for the user to see the update notes provided in the appcast.xml file by the stack developer when the end user is updating a single stack.

**Comment by yourhead** [comment]
I've added a number of ways for users to see the release notes:
- if updates a small number of items (< 4) then the release notes will open automatically in a browser.
- there will be a "Open Release Notes" item on any stack that is marked as needing an update.
- clicking the "i" button next to the update warning text will open the release notes.

i have some ideas for some further enhancements, but i think this is a good start
