### ISSUE TITLE
clearValue array not functioning for input arrays

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#277]
If you have an input array, and try to create a `clearValue` array, then only the first value works on the first field. Subsequent clear values in the array do not work.

**Comment by yourhead** [comment]
can you provide a concrete example how to duplicate this. i see something similar -- however this bug report is ambiguous enough that i could be fixing something that isn't the bug that you see.

**Comment by joeworkman** [comment]
clearValue.devstack is on our share... once you have more than 2 inputs, the clearValue is unpredictable.
