### ISSUE TITLE
%text% inside of <p> Tag does not get rendered inside of said tag while in Edit Mode

### ISSUE THREAD

**Issue by bbyrdhouse** [yourhead/s3#286]
Whenever you use the %text% macro inside of a `<p>` tag like this:

```
<p>%text%</p>
```

The resulting html does this:

```
<p></p>
<div class="out" id="stacks_out_46_page0" uid="E8A74D4D-9C44-4066-9730-5887450F7C4C"><div class="mez pinned node" id="slice_mez_46_page0" uid="E8A74D4D-9C44-4066-9730-5887450F7C4C">
<div tag="button" type="pin" uid="E8A74D4D-9C44-4066-9730-5887450F7C4C" class="stacks-button pin"><i class="fa fa-thumb-tack"></i></div>
<div tag="node" uid="E8A74D4D-9C44-4066-9730-5887450F7C4C" id="stacks_in_46_page0" style=" min-height:20px;min-width:125px;">
Lorem ipsum dolor sit amet, ...
</div>
</div>
</div>

<p></p>
```

It puts it back in Preview and Publish mode but I would think that it should also be in a `<p>` tag while in edit mode.

**Comment by bbyrdhouse** [comment]
I should say that this creates a problem when I would need to add some styling to the content of the `<p>` tag while in Edit mode ... there is no way to target that content if the surrounding tag is stripped away in edit mode.

**Comment by atavernor** [comment]
Just give it an edit mode only div with a class to target

`%[if edit]  <div class="my-style">%[endif]%`
`%[if !edit]% <p>%[endif]%`

`%[if !edit]% </p>%[endif]%`
`%[if edit]% </div> %[endif]%`

Your css can then just target .my-style and p  all the time - it won't matter that one or the other is missing in edit or preview/publish or you could do likewise in the css but that seems an unnecessary introduction of expensive api logic.

This way the %html= won't break the `<p> </p>` apart

**Comment by bbyrdhouse** [comment]
Yes, I am aware of how to go around it but to me it looks like a bug so I reported it. Perhaps it is intended behavior and that is fine too, but at least it is reported and Isaiah can decide what to do with it from here.

**Comment by atavernor** [comment]
Sorry didn't mean to condoned - it is an HTML thing though as far as I'm aware. `<p>` tags never allow block level items within them.

**Comment by bbyrdhouse** [comment]
No problem ... Ahh ... so its not really a Stacks thing then ... its Webkit probably doing it.

**Comment by atavernor** [comment]
yep
