### ISSUE TITLE
FontAwesome is not loading async when set

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#287]
I set the async flag for Font Awesome to true. However, it does not get loaded asynchronously.

**Comment by joeworkman** [comment]
Here is the JavaScript to load FontAwesome Asynchronously. I cannot stress how much faster this makes pages loads... 

```
// loadCSS v0.1.5 - https://github.com/filamentgroup/loadCSS
function loadCSS(href,before,media,callback){"use strict";var ss=window.document.createElement("link");var ref=before||window.document.getElementsByTagName("script")[0];var sheets=window.document.styleSheets;ss.rel="stylesheet";ss.href=href;ss.media="only x";if(callback){ss.onload=callback}ref.parentNode.insertBefore(ss,ref);function toggleMedia(){var defined;for(var i=0;i<sheets.length;i++){if(sheets[i].href&&sheets[i].href.indexOf(ss.href)>-1){defined=true}}if(defined){ss.media=media||"all"}else{setTimeout(toggleMedia)}}toggleMedia();return ss}

loadCSS('%siteAssetPath%/font-awesome.min.css');
```

**Comment by yourhead** [comment]
as much as i like this idea, i'm hesitant because it means that i break my "stacks doesn't have its own JS" rule.  and that tends to be a real life-saver when trying to cut through the chaff of complex support problems.

i think what i'd like to do is add this, but not on 3.0 -- i'm going to sneak it into a later release

**Comment by yourhead** [comment]
sorry, i'm not going to add this. there are too many variants of async loaders right now. and there seem to be view best practices. large, fast, and seemingly great sites are not doing what google requires for page-speed relevance.

the main worry is that i will choose one thing -- but the web will converge on another -- and i'll be stuck supporting an api that does the wrong thing.

i think we should wait another 12 months to see if something shakes out before we write this in the indelible ink of the API before considering to add something like this.
