### ISSUE TITLE
There is no undo the process of creating a partial

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#290]
If I try to create a partial, its a one way street. I cannot decide to go back. Then if I click done, I cannot make my layout not be a partial now.

**Comment by ghost** [comment]
essant on the Slack channel found a sort of solution to this:
"You can cut and paste a stack out of a partial back to the stacks page"

**Comment by yourhead** [comment]
i don't think it should be cancelable -- the push-navigation stack ux isn't actually modal -- so i don't think cancel is appropriate. however it will be undoable like any other action in stacks. i think that's the right thing to do here.
