### ISSUE TITLE
Inline math for if statements always return float

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#293]
If you use inline math within an if statement, the results seem to always return a float instead of an integer. When I then compare the results to a value, it breaks. 

I placed `ComplexIF.devstack` on our Dropbox share that illustrates the bug. 

This example works in Stacks 2.

**Comment by yourhead** [comment]
i can't duplicate this one. or probably more accurately, i'm not sure what you mean.

it would be helpful if you provided a simple one line code snippet that shows the behavior and told me what to look for in specific.

**Comment by joeworkman** [comment]
Three liner... This works in Stacks 2, not in Stacks 3

```
%[if %(%(20 - %(5 * 2)%)% <= 0)%]%
    <p>Complex IF works if you don't see Stacks API around this</p>
%[endif]%
```

**Comment by joeworkman** [comment]
Updated stack on share with simpler example

**Comment by joeworkman** [comment]
20 - (5*2) returns 10.000 instead of 10

**Comment by yourhead** [comment]
you have 4 things going on here:

a multiply
a subtraction
a compare
a conditional

are all of these necessary to see the problem?  

is the problem with one of them in specific?

> 20 - (5*2) returns 10.000 instead of 10

although that is different than stacks 2, i don't really see that it is a bug per se. does this cause a problem somehow? if so, can you be specific about how/where i should look to see the problem?

**Comment by joeworkman** [comment]
This is in an older stack and I probably would never do this the same way again. But the behavior does diverge from S2 so I thought that I would point it out. 

I can update my stack so that it works in S3 if you decide that is the best way.

**Comment by yourhead** [comment]
you're missing the point...   i think this is a bug. but you're being very ambiguous in your description. so much so that i'm not sure if the bug i'm fixing is the bug you've reported.

s3 now supports float calculations -- so a multiply returns a float -- i don't see that as a bug (it's a feature).

i **think** the bug that you're reporting is that a float can't be used in a compare or **maybe** it's that a compare with a float as an input can't be used inside a conditional. or maybe something else ???    but it's hard to tell.

**Comment by joeworkman** [comment]
So I tested this again in Stacks 2... 

The equation returns an integer in S2. Returns a float in S3. 
Comparing a float to an integer in both S2 and S3 does not work.

**Comment by yourhead** [comment]
I believe this behavior is actually the result of two interrelated bugs. I've filed two reports that more precisely document the current behavior:  #309 and #310
