### ISSUE TITLE
Font Awesome font files not loading

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#294]
The font awesome css is referencing the font files at `../fonts/`. That path needs to be removed from the css.

**Comment by yourhead** [comment]
can you be more specific please

**Comment by joeworkman** [comment]
If you look at the `font-awesome.min.css` that ships with Stacks 3, if references the font files as... 

```
@font-face{
font-family:'FontAwesome';
src:url('../fonts/fontawesome-webfont.eot?v=4.3.0');
...
}
```

Note the `../fonts/` path. That is not where Stacks puts the font files. You will need to remove that path from the src url and only have the font file name since they live in the same directory as the css file.
