### ISSUE TITLE
Color control: default value -  integer values fail  while % values work as expected (in non-arrayed controls)

### ISSUE THREAD

**Issue by atavernor** [yourhead/s3#299]
With allowsOpacity enabled:

Setting the default to rgba(255,255,255,0.5)  yields a black default color well.

Setting the default to rgba(100%,100%,100%,0.5)  works as expected and yields white at 50% opacity.

**Comment by yourhead** [comment]
i copied and pasted both of these values into the OMG Controls example stacks as the defaults for the 2-color well.  It behaved as expected.

![skitched-20150717-175939](https://cloud.githubusercontent.com/assets/98634/8758760/98e81fc6-2cad-11e5-85c7-bc9c7a46e054.jpg)

![skitched-20150717-180002](https://cloud.githubusercontent.com/assets/98634/8758764/a68de6d8-2cad-11e5-9fe8-faa3848957c3.jpg)

**Comment by yourhead** [comment]
my guess is that the devil may be in the details, perhaps the whitespace in your stack is slightly different and is throwing off the parsing.  i tried a few things but didn't hit on what it might be.

**Comment by atavernor** [comment]
OK, thanks. I will re-visit it and try again

**Comment by atavernor** [comment]
I replicated your experiment and got the same correct behavior with the button-2 control but still failed with a single button 

<img width="869" alt="screen shot 2015-07-18 at 00 07 41" src="https://cloud.githubusercontent.com/assets/8500380/8758848/62073710-2ce1-11e5-9149-72a84750c50e.png">

**Comment by yourhead** [comment]
requires:
- the non-arrayed color well control
- arrayed default value
