### ISSUE TITLE
Unregistered installation limits layout ot 4 stacks

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#30]
There is no current way to register stacks.  And there is no feedback to let the user know what's happening.

**Comment by yourhead** [comment]
The description is not repeatable.
This is likely the side effect of some more nuanced bug.

**Comment by doobox** [comment]
Looks like this is a small screen issue. I can't repeat this on mac book pro retina now. But can continue to repeat this without fail on the 11" mac book air.

**Comment by yourhead** [comment]
I'm afraid that's unlikely.  I have tested on a small screen.  It's likely something else.  If you could provide some more details, or perhaps try the drag and drop with other stacks, or perhaps try it on a new file, or perhaps try it on in different view modes, or...   you get the idea.  

This is clearly repeatable sometimes but not at other times.  We need to know what those times are.

**Comment by yourhead** [comment]
gary reported that it went away after a reboot.
closing until more data is available.

**Comment by yourhead** [comment]
- verified to be only when using an unregistered copy of stacks
- fixed in alpha 2
