### ISSUE TITLE
requiresPHP does not change page name to .php

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#303]
1. Add a stack to a html page that has `requiresPhp` set to true. 
2. Look at the page name and it does not change to php.

**Comment by yourhead** [comment]
works for me

**Comment by yourhead** [comment]
note: the RW sidebar doesn't update immediately -- you have to switch pages and switch back to see the filename update. but that's a long standing RW behavior/bug.

**Comment by yourhead** [comment]
i've reported this bug to RMS.
