### ISSUE TITLE
Stacks adds a Green and Blue background of addType items

### ISSUE THREAD

**Issue by bbyrdhouse** [yourhead/s3#306]
As mentioned a couple days ago in the Slack group. 
When using the addType feature Stacks adds a green or blue background when in edit mode. 

Note the image below: 

<img width="891" alt="s3_addto" src="https://cloud.githubusercontent.com/assets/7376298/8761468/68125bee-2d18-11e5-84df-f39ceb67a907.png">

**Comment by yourhead** [comment]
the green was easy to track down -- but the blue...  is that a selected stack?  if so, then i think that might be intentional.

also:  your "+" button looks mangled -- what happened?

**Comment by bbyrdhouse** [comment]
The blue is selected ... 
The '+' button does look wonky but I'm not sure why ... it just looks that way. It didn't use to.

**Comment by yourhead** [comment]
ok. i'll just leave the blue be. thx.

i suspect that there's some CSS in your stack that's killing the plus button. you might want to see if you can track that down
