### ISSUE TITLE
some users see generic squares instead of drop arrow icon

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#315]
one user reports only on brand new pages with no stacks.

**Comment by joeworkman** [comment]
I wonder if that has to do with the Font Awesome loading that was filed in b6?

**Comment by yourhead** [comment]
yes. i see now that i've been ping-ponging back and forth between FA working in published pages and FA working in edit mode.

i need a separate version of FA edit mode.  no big deal.

**Comment by DeFliGra** [comment]
Two users. Brand new Mac... almost. Pretty clean RapidWeaver install. Only use the Macbook Air for testing, email & browsing/social media.

Note that all Control Panel categoris start open. Maybe it's intended.

![macbookair](https://cloud.githubusercontent.com/assets/1144917/8783407/e8f351fa-2f1b-11e5-8abf-e59af701a9ee.png)

**Comment by yourhead** [comment]
when an issue is naked "completed" it means it's already been fixed. no need for anything further on this one, thx. the fix should be in the next release.
