### ISSUE TITLE
Install Update will browser with release notes every time

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#317]
When selecting a dedicated stack -> Install update, the browser will open with the release notes. That might be ok for one dedicated stack
But when selecting Library -> Install all updates, all release notes for all updated stacks are opened, which will result in n - open browser windows.

**Comment by yourhead** [comment]
Not every time. It will open 4 tabs.  More than that it assumes that the user doesn't care and just does the install quietly.
