### ISSUE TITLE
Sparkle update of a main Stack does not updated inside stack

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#318]
I have a main stack (with appcast, which includes a second stack inside (w/o appcast).
Sparkle update of the main stack updates the main one, but the inside one is not updated.
After RW restart, all is fine, inside stack is also updated.

**Comment by yourhead** [comment]
so, to confirm:   the update takes place in the file-system but is not reflected within stacks?

**Comment by jrondorf** [comment]
I will check...

**Comment by jrondorf** [comment]
No, don't have to. You are right.
