### ISSUE TITLE
old-style-jQuery declaration ignored when new libraries API is used

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#320]
I migrated a stack to use Font Awesome via `libraries`. The stack also used jQuery but I still was using the `javascriptLib` key. When you have this combination, the javascript closures seem to be removed. I was getting an error that jQuery was not defined in my stack. 

The only fix was to load jQuery via `libraries`. This did fix it.

**Comment by joeworkman** [comment]
I added my Glider stack to our share that displays this behavior. Just add it to the page and you will see the errors.

**Comment by yourhead** [comment]
I added the glider to a page. And that page seems to have a closure. And the closure seems to have the glider content.
I'm not really sure what else to try. I don't really know what I'm looking for.

Is there something I need to do to make it happen?  Is there a different closure you're expecting?

**Comment by joeworkman** [comment]
320-LibraryClosureBug.mov on our share. Repeats for me every time

**Comment by yourhead** [comment]
Ah...   I see jQuery is missing you from the stack -- i still don't understand how you got to closures...   but anyway... that's the expected behavior.

you declare jQuery with the old API and fontAwesome with the new API.  the new API supersedes the old one, if you want to use the new API, you need to define jQuery there too.

**Comment by yourhead** [comment]
![skitched-20150721-192205](https://cloud.githubusercontent.com/assets/98634/8815372/c6578cfc-2fdd-11e5-8713-d5c8417e9af5.jpg)

with this change the stack works as expected
