### ISSUE TITLE
library width is not remembered all the time

### ISSUE THREAD

**Issue by girlcarew** [yourhead/s3#323]
open RW doc
drag library sidebar to a smaller size.
then stop dragging and let go of the mouse.
now drag the library side bar closed
click the library button to open the window
the library size is NOT where you had dragged it to but it should be.

**Comment by ghost** [comment]
I'm assuming its the same thing but I'm mention it anyway.
I drag the Library pallet slightly wider than the default so that I can see the 1st one or 2 letters of group titles but whenever I reopen RW it defaults back to the icons only width.
