### ISSUE TITLE
Release Notes URL in plist

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#327]
This would be very beneficial in order to display the complete release notes history for a stack. This is important in case the user updates a stack and wants to know what in the world changed after the fact.

**Comment by yourhead** [comment]
you can put it in there if you want. it won't hurt anything. there isn't a UI to take advantage of it right now tho.

**Comment by joeworkman** [comment]
Put it in with what plist key? Was this something that I overlooked? Or are you referring to the support url?

**Comment by yourhead** [comment]
Sparkle uses: "releaseNotesLink"  -- let's keep that.
