### ISSUE TITLE
Stacks CP settings disappear randomly

### ISSUE THREAD

**Issue by DeFliGra** [yourhead/s3#328]
Sometimes settings in the Stacks Control Panel disappear. Happes when all groups are closed and groups are opened again a from bottom to top.

I've tried opening the groups from top to bottom one at a time > seems to work okay.

Problem found when doing it reverse or opening a group in the middle.

**Comment by yourhead** [comment]
I've seen this too.  However, it's always very intermittent. I cannot duplicate it with any reliability -- which makes it impossible to fix.  I've been trying to find this for (no joke) months.

Can you provide a specific set of steps with a specific stack that makes this happen every time?

**Comment by DeFliGra** [comment]
Same here > can't find a pattern.

But seems to happen often the more control panel settings and control panel groups... which probably makes sense > since there's more more settings to do the damage.

I'll go through couple of the stacks that 'loses settings' to see if it happens say 10 times in a row and I'll mail that stack to you.

Here's a Spielberg showing the 'random' issue: https://db.tt/iuLWbl7l

**Comment by DeFliGra** [comment]
I've found one pattern. If I open a control panel group, close it, open the next, close it... so on > everything work fine. All settings are visible.

But if I open 1 + next + next + next + next + next... doesn't matter if it's from the top of the group or from the bottom of the group > settings go missing somewhere.

I'll be sending you a button stack. I've repeated the issue 10+ times. Settings always goes missing in group 6 or 5. When I start from top it's in this case most often the group called 'Content'. If I start from the bottom it's the group below called 'Style'.

Stack on it's way by e-mail within seconds.

**Comment by girlcarew** [comment]
So, I installed the Click Master Demo" stack that you sent, but I can't reproduce the problem. First, can you make sure you're using the latest beta (b6)?
Then, when I select the Click Master Demo stack, in my prefs (what you call the CP) all the settings are open. Does it matter how I close them? In any particular order? If I just close them all and then try to open them from bottom to top, everything seems fine.
Can you tell me exactly what you do (what order, etc).?

**Comment by DeFliGra** [comment]
First thing first. I've got b6 installed on my machine.
Downloaded yesterday 21.29 my local time.

![b6](https://cloud.githubusercontent.com/assets/1144917/8782208/33f6d436-2f14-11e5-8b22-11e7d4b405cc.png)

**Comment by DeFliGra** [comment]
Second thing... now you mention it.

All settings opened... that's probably another issue!

If I drag a new stack that I haven't used before to a stacks page – all settings start out opened!

Then I close them. If I close the document again. Save. Quit. Reopen. Then drag same kind of stack to the page it will start out closed (the way I left it).

I thing that the Stacks plugin remembers how I left my Stack last time I used it. Which Control Panel (pref) categories I left open > and it will deliver the same setup.

It does that with all new stacks I drag to a page. Starts with all ControlPanel options open.

You can't probably – I would imagine – repeat this... because the stacks you have on your system have been used during the process? Other devs might wanna step in to confirm if this is an issue or... maybe just on my machine.

**Comment by DeFliGra** [comment]
Third... doesn't seem to matter in which order Control Panel Categories are opened. 
From top to bottom. From bottom top top. Random here and there.
I have the same issue... sometimes settings disappear.

**Comment by joeworkman** [comment]
I found the issue! Your Finder is full of gibberish! ;-)

**Comment by yourhead** [comment]
Without steps to repeat this issue. It's DOA. Sorry. I'm going to have to close. I'll reopen if someone can provide steps. Thx for trying everyone.

**Comment by DeFliGra** [comment]
Year... probably, Joe. I have a MacBook Air clean RapidWeaver + Stacks install – no third party stacks installed – just for testing. I'll make an exception and install a few. If we're lucky... I will not be able to replicate this issue I'm having on my working machine 27" Mac. And then all is good.

**Comment by joeworkman** [comment]
@DeFliGra I was purely joking... :-)

**Comment by DeFliGra** [comment]
Well... it's a very relevant joke. With all the software we have installed > conflicts will happen. It's pretty much like a 7 year old marriage.

But I do have a brand new... Mac to test things.

**Comment by DeFliGra** [comment]
Can't replicate it on my MacBook Air.
Settings only dissapear on my WorkMac = 27" iMac... with tons of RW Stacks.
