### ISSUE TITLE
Author should not be the default grouping

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#33]
Just opened S3 for the first time with my entire stacks library loaded.

Expected to see all the stacks still grouped by the plist group key.

Actual result : All my stacks and most other developers stacks are in the "unknown" group.
There are even sone of my stacks believing they belong to a group called "Copyright@2015 Doobox" obviously picking up my copyright plist key.

**Comment by yourhead** [comment]
I'm going to take this as the default behavior of the grouping is too confusing.  But it would be good to have something specific to say whether this is fixed or still broken.  If you'd like to add to it, that would be helpful.
