### ISSUE TITLE
Plist Info String doesn't reflow in CP Sidebar

### ISSUE THREAD

**Issue by DeFliGra** [yourhead/s3#330]
Lot of stacks has a little info here and there – they don't reflow like in prev. version.
To make the info reflow the info text will have to have an option-return.
Lots of stacks from all devs. will need to rework their info if it's intended.

**Comment by yourhead** [comment]
Can you be more specific. I'm not really sure what you're talking about.

**Comment by DeFliGra** [comment]
Screendump attached.

The text 'Portion of the YouTube url after... doesn't reflow to the next line like it did in Stacks 2.x. Just continues without reflowing to next line.

To make it reflow (like it would in any word processing app when the end of a line was reached) an option-return have to be added somewhere in the text. 

![long-info-text-controlpanel](https://cloud.githubusercontent.com/assets/1144917/8777676/c56b5df8-2ef9-11e5-941d-0320cc158d39.png)

**Comment by girlcarew** [comment]
What stack is this?

**Comment by DeFliGra** [comment]
Gary's Play Stack. Just one example. Same happens to all stacks – on my mac – where text used to reflow on two lines > now the don't reflow but are kept on line 1.

It's no big deal – devs will just have to option-return line one where they want line to be divided.

**Comment by DeFliGra** [comment]
Tested on my second Mac > Macbook Air > Same 'issue'. Info text doesn't reflow (screendump above) > as it did in Stacks version 2.x. Same Stack tested. Same 'issue'.

But as mentioned > no big deal > devs will just have to adjust the length of the info.
