### ISSUE TITLE
Pasted image in Text stack not exported correctly

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#332]
- Create a new Stacks page, add default stack "Text" to it.
- Drag and drop an jpg image from your desktop to the text area.
- Looks good in edit and preview mode.
- When exporting the whole project to a local folder or publishing to a FTP server, the image is not displayed, because it is references from the local work folder like this:
  /var/folders/jm/nbr18v4d0zs4wt48gzk7djwh0000gn/T/com.realmacsoftware.rapidweaver6/stacks-5087B27A-C13B-4107-BE00-A97904FFE61C-m01y3x/files_0CCA061C-A691-476C-84B3-8E5FA0BC7F7D_174/../screenshot.jpg

Website example: http://test.instacks.com/image/
Demo project: http://test.instacks.com/image/test.rw6.zip

**Comment by yourhead** [comment]
good catch! thanks!
