### ISSUE TITLE
All Stacks Control Panel Categories start open

### ISSUE THREAD

**Issue by DeFliGra** [yourhead/s3#334]
When adding a Stack that has not been added to the page before – the stack will start with all Stacks Control Panel options (pref setting / hud settings) open.

Replicated on 27" iMac + Clean RW Macbook Air install.

Reported in another thread about another issue.

**Comment by yourhead** [comment]
i'm afraid i do not see this behavior at all.  what i tried:
1. Add a text stack.
2. Hide the "Layout" group
3. Add an HTML stack.

Layout group is hidden as expected.

**Comment by DeFliGra** [comment]
Have you tried with a completely new stack never installed in your system before? One you haven't worked with? The issue might be that.

All stacks I have worked with before works and are left the way I've left it.
New stacks I haven't worked with > all start open.

**Comment by DeFliGra** [comment]
The problem is almost non-existent when dealing with simple stacks with only few categories of settings in the Control Panel (Prefs, Hud).

https://db.tt/Yzt8z05M

When dealing with more complicated stacks with lots of settings – users will have to close every category first – to get an overview of settings/categories.

As mentioned this happens on both of my Macs. Could be nice to hear if this happens to some of the other developers with more complicated Stacks.

**Comment by yourhead** [comment]
Give me some instructions on repeat this and i will reopen. I've already wasted too much time hunting for it. I can't afford any more. Sorry.
