### ISSUE TITLE
Change new responsive settings to use a class for hiding. 

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#336]
This would allow me to customize the breakpoints of these settings in Foundation so that they break at the same time as the rest of Foundation does. 

Right now they are done via the stack ID. This makes it impossible for me to tweak.

**Comment by yourhead** [comment]
it's not 100% clear what you're requesting. and i must admit with only a few days before release it's probably a lost cause.

**Comment by yourhead** [comment]
// desktop
@media only screen and (min-width: 771px) {
.stacks_l_hidden { display:none; }
}

// tablet
@media only screen and (max-width: 770px) and (min-width: 441px) {
.stacks_m_hidden { display:none; }
}

// mobile
@media only screen and (max-width: 400px) {
.stacks_s_hidden { display:none; }
}

**Comment by joeworkman** [comment]
👊 #bahlalala
