### ISSUE TITLE
Search with zero or few results still displays large scrollable area

### ISSUE THREAD

**Issue by NimbleHost** [yourhead/s3#34]
When searching the library such that zero or only a few results are listed, and those results can all be displayed in the currently visible library area without the need for a scrollbar, a scrollbar is still displayed and the library can be scrolled past the listed items so that no stacks are visible.

**Comment by yourhead** [comment]
#1:  please don't post screenshots.

**Comment by NimbleHost** [comment]
crap, sorry, forgot this was public

**Comment by yourhead** [comment]
i know. i should really give people a reminder.

**Comment by yourhead** [comment]
but, yes...  i know about these bugs.
they're relate to the semi-transparent (vibrant) views.

**Comment by NimbleHost** [comment]
totally my fault, I should've remembered

**Comment by yourhead** [comment]
mac os x assumes you want to scroll to see under them -- even if there's nothign to see there

**Comment by yourhead** [comment]
fixed in beta 2
