### ISSUE TITLE
3 char units go right to the window edge

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#340]
When you have a 3 char unit for a number, the label goes right to the edge. However, when you have more than that, Stacks seems to shift the text over a bit so that it does not butt with the edge of the window.

**Comment by joeworkman** [comment]
![screen shot 2015-07-21 at 6 53 25 am](https://cloud.githubusercontent.com/assets/225628/8802346/a77fc00a-2f75-11e5-9823-22bbc72bd79f.png)

**Comment by joeworkman** [comment]
![screen shot 2015-07-21 at 6 57 02 am](https://cloud.githubusercontent.com/assets/225628/8802354/b8bffac4-2f75-11e5-93f4-23c23bc4b804.png)

**Comment by yourhead** [comment]
yep. we're all out of space. i have to take away space from somewhere to give it to another place. so i can:
- take away from the title -- but then we risk that some stacks that had very long titles will not be usable --   so, that's a no-go.
- take away from the middle -- but some controls like number-4 are already very very tight.
- make larger controls misalign in comparison to other controls.    ha ha ha...   only joking. that's not actually an option.

i think smashing the units is the best of those. it's not a usability concern, just a cosmetic one -- and way better than misaligning things.

in later updates where i'm not as concerned about maintaining 100% backwards compatibility (when there's no paid upgrade) we can perhaps steal 4px from the title, which should be plenty.

**Comment by yourhead** [comment]
I think I've done as much as I can for this one -- the new flexible windows make a lot of things pretty restricted.
