### ISSUE TITLE
Images library open at first install/launch of S3

### ISSUE THREAD

**Issue by leifottosson** [yourhead/s3#341]
I just realized that the images library was open even though it was unchecked in the prefs settings. After checking/unchecking it's closed and I can't replicate the issue again. It seems like this happens on the first install/launch and that it stays open until you check/uncheck in the prefs settings. Quitting and restarting RW didn't make any difference.

**Comment by yourhead** [comment]
good catch! thanks!
first launch bugs are so hard to find!
