### ISSUE TITLE
Deleted stack don't disappear

### ISSUE THREAD

**Issue by leifottosson** [yourhead/s3#342]
Used the search field to filter stacks.
Deleted one of the filtered stacks.
Stack did not disappear, was still in the library.
"Closed" the search (x) and when scrolling to the place where the stack was earlier it was gone now.

**Comment by yourhead** [comment]
can you explain what you mean by "deleted" -- do you mean "Uninstall"? Or something else?

**Comment by leifottosson** [comment]
You're right Isaiah, the correct word is uninstalled, not deleted.
