### ISSUE TITLE
Changing a button setting to a checkbox = crash

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#344]
If you have a button setting and change it to be a checkbox but keep the same name. If you open a project that had an existing instance with the button, RapidWeaver will crash.

**Comment by joeworkman** [comment]
crash report: http://jwurl.net/1RNX5HY

**Comment by yourhead** [comment]
"a button setting" -- so you mean in a custom stack?  Or like a button on a web page? or something else?

**Comment by yourhead** [comment]
"and change it to a checkbox" -- do you mean change the "type" key to "checkbox" from "button"?

**Comment by joeworkman** [comment]
Correct. I changed a button type to a checkbox

**Comment by joeworkman** [comment]
The setting was originally a checkbox. I changed it to be a button just to see how it would look. Going from checkbox to button was ok. I did not get any errors. However, when I switched it back to checkbox, it caused RapidWeaver to crash when the stack already existed on the page. I knew exactly what I did but thought that you may want to see the crash report in case it happens to someone else.

**Comment by jrondorf** [comment]
I've had the same in S2 when changing a input field to a link, so I stopped and used another way...

**Comment by yourhead** [comment]
In general I strongly recommend against changing the "type" to another. It will almost always cause a crash -- it only kind-of-sort-of works in some cases where types are mostly compatible.

I do want checkboxes and buttons to be roughly interchangeable, so i'll make an exception in this case.
