### ISSUE TITLE
Request for number-3 settings type for plist

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#346]
There is 2/4 but I would like to have the option for 2 number boxes.

**Comment by yourhead** [comment]
it doesn't align to the grid.
my OCD says **request rejected**

**Comment by joeworkman** [comment]
Damn your OCD!!! I need color-3 as well...

**Comment by elixirgraphics** [comment]
I too could use `number-3` and `color-3` controls. I mean they could then hang out with `button-3` and he wouldn't feel like a loner.
