### ISSUE TITLE
Stacks that contain a css library flicker when any setting has changed

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#347]
If you have a stack that contains a css library, then whenever you change any setting inside that stack, the stack has a nasty flicker in Edit Mode. 

I have uploaded a video and my latest version of my Foundation stack that illustrates the issue.

**Comment by yourhead** [comment]
a video of the issue only helps if i didn't believe you. but i do believe you. when you say it flickers...   it does.

but i would like you to tell me how to make that happen. I would wager that this is highly dependent on a number of plist settings and what CSS is in the file and that my liklihood of stumbling on the correct ones is close to 0%

**Comment by joeworkman** [comment]
LibraryFlicker.devstack is on our share. There is one setting and it still flickers.

**Comment by yourhead** [comment]
it wouldn't flicker if you didn't override the whole UI.  ;-)

we can put all this CSS in the head -- that's what we were doing before -- but that incurs a huge performance cost
or we can put it locally with the content of the stack -- but if there's a lot of styles, then there's going to be a noticeable time to render that content every time a template changes -- and that's what you've got here.

i'll see if there's any low hanging fruit here to make this better, but i think this is pretty much what we've got.

also:  i've noticed that a number of your styles are really bashing the UI quite a bit. i'd really prefer if you didn't do that.

**Comment by joeworkman** [comment]
So after restarting RapidWeaver. The flicker seems to have stopped in my Foundation stacks. However, it still happens in that Flicker stack. That is perplexing.

**Comment by yourhead** [comment]
i definitely saw the flicker myself. and it seemed quite obvious what was happening. i'm going to give this some more thought, but right now i'm not seeing too many ways to work around this. it's a tough one.

**Comment by yourhead** [comment]
hopefully this will be a non-issue with the changes made today
