### ISSUE TITLE
Name of partial is getting cut off in edit mode

### ISSUE THREAD

**Issue by leifottosson** [yourhead/s3#352]
![partial-name](https://cloud.githubusercontent.com/assets/5895269/8846684/5c466264-3129-11e5-8aab-67515cdc4b8a.jpg)

**Comment by joeworkman** [comment]
Not a Stacks bug... Next Foundation update will fix.

**Comment by leifottosson** [comment]
Ok. With so many 3rd party devs out there it's hard to know who's to blame...  ;-)

**Comment by joeworkman** [comment]
I believe that Isaiah is working so that things like this wont happen in future builds.

**Comment by yourhead** [comment]
next build should be much better. the styles of these parts should be less affected by the global styles that Foundation applies.
