### ISSUE TITLE
Deleting a stack using the "Delete" button on the keyboard AFTER a stack has been edited sometimes replaces the stack with a new stack

### ISSUE THREAD

**Issue by bbyrdhouse** [yourhead/s3#357]
**Step 1:** Open a new project and add a Stacks 3 page and then add a text stack (an html or Markdown stack also works)

**Step 2:** Edit or replace the default content in the stack then click out of the stack

**Step 3:** Select the stack and then delete the stack by hitting the 'delete' key on your keyboard

This results in Stacks either reverting back to the default content or replacing the stack with a new stack of the same type as if it had just been dragged onto the canvas (I suspect the former).

Here is a brief video demonstrating it in action ... 

http://cl.ly/2r0h3L2i2n0c

**Comment by yourhead** [comment]
this is the intended behavior.
if you select a content area within a stack (a text stack just has one center text area -- but many stacks have more), then type delete you "Clear" the content area without deleting the whole stack.

this is a long-standing feature of stacks (although has been subtly modified in each major version).

In stacks 2 you'll notice that the red "Delete" button changes to "Clear" in this situation.
