### ISSUE TITLE
Images in columns does not align

### ISSUE THREAD

**Issue by leifottosson** [yourhead/s3#359]
Add 3 col stack (standard bundled stack).
Add 3 images.
Use Tesla bundled theme.
Result - see screenshot.
Same error for 4 and 5 col stacks too.
![3-col-error](https://cloud.githubusercontent.com/assets/5895269/8883559/ec5f3b2e-324f-11e5-869f-fc5cf49c1515.jpg)

**Comment by yourhead** [comment]
can you send me a copy of this theme privately?

**Comment by leifottosson** [comment]
No need for that, it's the Tesla theme that comes with RW6. One of the 5 new themes.

**Comment by leifottosson** [comment]
There's more problems with this. Sending you more info and a video via Slack.

**Comment by yourhead** [comment]
super. thanks. all fixed. will be in the next versoin.
