### ISSUE TITLE
Checkbox default true/false value

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#360]
Referring to: http://yourhead.github.io/StacksAPI/controls/checkbox/index.html
### True Value
- Key:trueValue
- Type:boolean
- Default Value:1
### False Value
- Key:falseValue 
- Type:boolean
- Default Value:0

When using this plist entry, trueValue is string "True", falseValue is string "False".

I expected to have trueValue = 1, falseValue = 0

```
    <dict>
        <key>default</key>
        <false/>
        <key>id</key>
        <string>localize</string>
        <key>title</key>
        <string>Some Title</string>
        <key>toolTip</key>
        <string>Some Tooltip</string>
        <key>type</key>
        <string>checkbox</string>
    </dict>
```

**Comment by jrondorf** [comment]
Same for this kind of plist entry:

```
    <dict>
        <key>default</key>
        <false/>
        <key>trueValue</key>
        <true/>
        <key>falseValue</key>
        <false/>
        <key>id</key>
        <string>localize</string>
        <key>title</key>
        <string>Some Title</string>
        <key>toolTip</key>
        <string>Some Tooltip</string>
        <key>type</key>
        <string>checkbox</string>
    </dict>
```

**Comment by jrondorf** [comment]
same for numbers. I guess only string works...

```
    <dict>
        <key>default</key>
        <false/>
        <key>trueValue</key>
        <integer>1</integer>
        <key>falseValue</key>
        <integer>0</integer>
        <key>id</key>
        <string>localize</string>
        <key>title</key>
        <string>Some Title</string>
        <key>toolTip</key>
        <string>Some Tooltip</string>
        <key>type</key>
        <string>checkbox</string>
    </dict>
```

**Comment by yourhead** [comment]
you're correct, there is a discrepancy between docs and behavior -- but just so you know, i think it's a documentation error.  checkboxes were the first custom control and as such come with a lot of ugly non-orthogonal legacy API baggage. 

however, i'll double check the behavior in S2 before changing anything and make sure behavior and docs are consistent with S2.

**Comment by yourhead** [comment]
I'm going to leave things as-is for the time being. I'm just worried that documenting this odd corner case would cause more confusion that it would solve.

I suspect that anyone that notices this very subtle discrepancy will have the wherewithal  to work around this behavior -- if it causes a problem at all.
