### ISSUE TITLE
FR: A macro that also includes the folder name after the base url ... 

### ISSUE THREAD

**Issue by bbyrdhouse** [yourhead/s3#364]
Example: 

%base_url% returns the base url just like it is expected 
%assetPath% returns the place where the stacks resources are located

What is missing (IMO) is the folder name in between the end of the base url and the resources folder ... 

Example: my-domain . com / folder/ files
![folder](https://cloud.githubusercontent.com/assets/7376298/8900119/38e52400-3402-11e5-89da-8a083f3473cf.png)

**Comment by yourhead** [comment]
http://yourhead.github.io/StacksAPI/templates/relativeDocRoot.html

**Comment by bbyrdhouse** [comment]
unfortunately that just returns a `../`

**Comment by yourhead** [comment]
maybe combine the relative path with the docroot.

if that's not what you're after, then you'll have to let me know more specifically what you need.

**Comment by bbyrdhouse** [comment]
Let me back up and try to explain this better .... 

Lets say that I have a file that is buried in my asset folder that I need users to be able see the path to this file.
I'll call this file `foo.php`
Because this file will always reside in the assets folder then its partial path will be `files/foo.php`

So I can use these macros to tell me the base url and the assets path:
`%base_url%%assetPath%/%id%_foo.php`

Which for example would produce: `http://my-base-url.com/files/foo.php`

But if the user is using a folder after the base url then there does not seem to be a macro that includes that folder: 
`http://my-base-url.com/FOLDER/files/foo.php`

Hope that makes more sense ...

**Comment by yourhead** [comment]
ah... you don't want the path "to" the docroot, you want the path "from" the docroot.

you want:  %pagePath%

http://yourhead.github.io/StacksAPI/templates/pagePath.html

**Comment by bbyrdhouse** [comment]
Bam! ... That is what I needed!

`%base_url%%pagePath%/%assetPath%/%id%_foo.php`

This produces the desired result for me.  Thanks!

**Comment by bbyrdhouse** [comment]
Ugh ... spoke to soon. `%pagePath%` functions very differently when the page is a parent vs when it is a child.

On a Parent: `%base_url%%pagePath%/%assetPath%/%id%_foo.php` produces
`http://my-base-url.com/folder/files/foo.php`

On a Child page: `%base_url%%pagePath%/%assetPath%/%id%_foo.php` produces
`http://my-base-url.com/.//folder/files/foo.php`
when, ideally it would produce `http://my-base-url.com/subfolder_files/foo.php`

**Comment by bbyrdhouse** [comment]
I don't think this is a bug, its probably how it is supposed to work.
Maybe, it could be added to the "One Day" list ...

**Comment by yourhead** [comment]
It's tough for me to parse out the various bits there.  Can you be more succinct in what the problem is.

**Comment by yourhead** [comment]
also...    it would probably be helpful to specify exactly which mode you're working in.  all path variables have 3 possible values for: edit/preview/publish   in some cases they're the same, but when it involves paths to/from the base then they're always going to be different in all 3 cases.

**Comment by bbyrdhouse** [comment]
I know, I'm sorry about that. It's difficult to express it from my perspective ... I know how much you hate pictures but maybe this will help.

I am using the exact same string of macros for both images, the only difference in the two images is one is a child page and the other is a parent page. 

PARENT PAGE: 
![parent-page](https://cloud.githubusercontent.com/assets/7376298/8919483/52197cae-3485-11e5-867d-9260ab5a8d52.png)

CHILD PAGE: 
![child-page](https://cloud.githubusercontent.com/assets/7376298/8919487/5cfb3fa4-3485-11e5-9f1b-f12e924a7f16.png)

**Comment by yourhead** [comment]
ok.  so you are trying to produce a Published URL from the Preview view....  yeah... that's always going to be challenging and error prone.

i mean, i'm happy to fix any bugs with this specific API -- but what you are attempting to do with it is...   well...   not something that either RW or Stacks supports directly.

in this case, Preview shows a specific page -- but the hierarchy is flattened so that RW only has to render that one page.  all of the stacks path variables produce output that's useful within that flattened hierarchy.  they don't produce the published paths until publish mode.

stacks (and RW itself) doesn't really have API to show the published hierarchy from preview or vice versa.

**Comment by bbyrdhouse** [comment]
ok ... its cool. Probably not gonna change any time soon I imagine.

I'll see if I can change something or add something to make it easier for users using the available tools.

**Comment by yourhead** [comment]
also:  i notice your #4  

you can make sure that your stack is always published on a php page
http://yourhead.github.io/StacksAPI/keys/requiresPhp.html

that will ensure the extension is php

**Comment by yourhead** [comment]
but if you think there is a bug in any of the specific items, just let me know.

there is a good resource for testing the various path expected values here:
https://github.com/yourhead/PathsTestStack
