### ISSUE TITLE
customItem of type number displaying unit string only after change

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#37]
When having a customItem of type number, and defining a units string like px, this is shown only after changing the value. E.g. below item will show only 200 when dropping it onto the page, not 200 px. Only if you change the number, px will appear.

Same behaviour as in Stacks 2.6.x :-)

```
    <dict>
        <key>units</key>
        <string>px</string>
        <key>min</key>
        <integer>1</integer>
        <key>max</key>
        <integer>1000</integer>
        <key>default</key>
        <string>200</string>
        <key>id</key>
        <string>width</string>
        <key>title</key>
        <string>Button Width</string>
        <key>toolTip</key>
        <string>Button Width</string>
        <key>type</key>
        <string>number</string>
        <key>enable</key>
        <dict>
            <key>id</key>
            <string>widthType</string>
            <key>value</key>
            <string>px</string>
        </dict>
    </dict>
```

**Comment by yourhead** [comment]
The issue here is that your default value is a the **_STRING**_ "200"  Although Stacks tries it best to convert this string to a number, strings cannot have units.  Try using an integer value and I think it should work fine.
