### ISSUE TITLE
A Stack installed by double click does appear in Stacks Library HUD only after restart

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#38]
If you double click on a stacks file, the Stack is added to the RW Addons Window, but not to the Stacks library HUD.

Only after RW restart, this new Stack is available there also.

**Comment by yourhead** [comment]
the installation process is mostly handled by the application. so it's not 100% certain that i can always make this work. but i'll give it a try.

**Comment by yourhead** [comment]
There isn't much I can do to change the application install process. I can add new ways (like via drag and drop into a stacks view) -- but double click is handle by the app itself.
