### ISSUE TITLE
Change of links in styled text stack does not set page to "changed" mode

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#380]
Put the default styled text stack on a stacks page. "Lorem ipsum"... will be inserted. Publish or export that page.

Double click into the text box, highlight one of the words, and select the "Link" button in order to set a link on the selected word, and set a link to any website.

This stacks page is then not marked as "changed". It will only be set into "changed" mode when actually changing some text, adding line feed, ...

**Comment by jrondorf** [comment]
![2015-07-30_15-20-49](https://cloud.githubusercontent.com/assets/2099795/8983971/9f3928e0-36ce-11e5-94fa-ef4c2a1297fd.png)

**Comment by yourhead** [comment]
weird.

**Comment by jrondorf** [comment]
weird, because you can confirm, or you can't confirm? :-)

**Comment by yourhead** [comment]
yes, confirmed.

weird because all that stuff is just part of RapidWeaver.  weird because it's probably a RW bug that i've somehow managed to avoid for 10 years.  ;-)

**Comment by jrondorf** [comment]
Now I caught you :-p

Standard RW styled text page does not have this symptom...
