### ISSUE TITLE
FontAwesome doesn't load Icon when called in css of a stack (In Edit Mode)

### ISSUE THREAD

**Issue by bbyrdhouse** [yourhead/s3#381]
When adding the FontAwesome Library via the plist. I can get Stacks to load the icon in Edit mode if it is called in the html like this:

```
<i class="fa fa-chevron-down"></i>
```

But I can not get it to load the icon in edit mode if it is called in the css like this: 

```
#%id% #sales-pitch ul li:before {
content: '\f05d';
font-family: 'FontAwesome';
font-size: 20px;
left: 0px;
top: 5px;
color: #3dc5df;
position: absolute;
}
```

**Comment by yourhead** [comment]
nope. that won't work. it's on purpose.   there are a few older stacks out there that include font-awesome and if Edit mode also includes it -- they fight.

so stacks includes font-awesome under a unique name.  if you change your call to look like this it'll work  (not the **font-family** line) :

```
#%id% #sales-pitch ul li:before {
content: '\f05d';
font-family: 'Stacks-FontAwesome';
font-size: 20px;
left: 0px;
top: 5px;
color: #3dc5df;
position: absolute;
}
```

**Comment by bbyrdhouse** [comment]
ok, gothcha ...
