### ISSUE TITLE
display file name of images

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#383]
My Jack stack ships with frames that can be used as border images. I named the images in a specific way so that the user knew how to make the settings for that particular frame. 

However, the image name is no longer displayed anywhere so users won't know this information now. I can think of 2 possible solutions. 
1. Display the image name inside the info box at the bottom of the library. 
2. Add a subtitle key to the media so that we can add text

option 1 seems easier but I am good either way.

**Comment by yourhead** [comment]
when you say "name" you mean the name of the file? or do you mean something else?

e.g.:  you'd like to display:  "plastic05-crop26.png"

**Comment by yourhead** [comment]
that doesn't look super user friendly or aesthetic at all.  what's the advantage of displaying that to the user? how will the use it? maybe we can solve problem in a way that's a bit friendlier

**Comment by joeworkman** [comment]
That is correct. I would like to display plastic05-crop26.png in the info pane. That "crop26" is the key.

**Comment by joeworkman** [comment]
I agree that displaying the name is not the prettiest and this is definitely an edge case. That is why I suggested a subtitle key for each media.

**Comment by yourhead** [comment]
I would rather not display it at all.  What is the value of displaying "crop26" to the user -- how do they use that?
