### ISSUE TITLE
Can not remove or delete a childOf item using addType

### ISSUE THREAD

**Issue by bbyrdhouse** [yourhead/s3#389]
When you add an item that is a childof using addType then there is no way to delete that item. You have to delete tho who stack and then re-add the stack and hope that you don't accidentally click the little blue '+' button again.

**Comment by bbyrdhouse** [comment]
Never mind this. I see that you have to click on the added item and then select 'delete' from your keyboard. Still, some sort of graphical notification would be nice.

**Comment by yourhead** [comment]
there should be a regular "close" button like every other stack. if there's not then it's a bug

**Comment by bbyrdhouse** [comment]
There isn't a close button.

**Comment by joeworkman** [comment]
Children in my childOf stacks have a close button

**Comment by bbyrdhouse** [comment]
They don't for me ... or maybe I'm holding it wrong.
<img width="1087" alt="s2 edits 1 2 4" src="https://cloud.githubusercontent.com/assets/7376298/9010141/ddef338a-376a-11e5-9e4b-3c029fcb1d63.png">

**Comment by yourhead** [comment]
it looks to me like you have all the outlines turned off on everything -- if that's the case, then the close boxes are meant to be hidden
