### ISSUE TITLE
Need to have a max childOf setting

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#390]
In order set a maximum number of children stack that can be added

**Comment by yourhead** [comment]
related to #160

**Comment by yourhead** [comment]
do you think #160 is enough for this one?

i can see that perhaps you might want to say:
- max of 2 image stacks
- max of 3 markdown stacks

-- but i'm not sure there's room in the stacks syntax for that.

thinking of calling this one done.

**Comment by yourhead** [comment]
closing in favor of #160
