### ISSUE TITLE
childOf add button DOM level

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#392]
Having the add button at the same level as the children divs makes for annoying CSS. It would be easier to style if it were maybe outside of the children wrapper div.

**Comment by yourhead** [comment]
i suspect you're just too late on this one.  i think there's several devs who have already spent months styling this...  if i changed now they'd lynch me.  sorry.

**Comment by yourhead** [comment]
if you want to get a quorum to get me to change, that's fine...  you'll need to convince doobox, exlir, and gary at a minimum.

**Comment by bbyrdhouse** [comment]
@joeworkman - Are you talking about the little blue button for addType?
