### ISSUE TITLE
Fill mode alignment does not always reflect what is shown on screen

### ISSUE THREAD

**Issue by girlcarew** [yourhead/s3#396]
Create a Stacks page.
Add a text stack.
Change the Fill Mode to Flexible.
Change the Flexible Width to 80%.
Change the Alignment to Left.
Change the Fill Mode to Fixed Size.

The "Align" now says "Center" but it shows as left. And I can't choose Center unless I choose something else first.

If I do choose something else, say "Right", then go back to Flexible. Then the alignment says "Left" but it shows right aligned.

**Comment by yourhead** [comment]
this is a longstanding behavior. changing it would break documents. we have to save this bug for a non-paid upgrade time.

**Comment by yourhead** [comment]
in beta 6
