### ISSUE TITLE
Link to RW resource looks strange

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#402]
When linking a resource file (in RW resources area), the link displays the internal RW structure, not the filename.

![2015-08-02_12-13-08](https://cloud.githubusercontent.com/assets/2099795/9025701/42e0db44-3910-11e5-97d0-0fb97c9d892c.png)

![2015-08-02_12-13-36](https://cloud.githubusercontent.com/assets/2099795/9025703/4b5c9a10-3910-11e5-900e-438195037299.png)

**Comment by jrondorf** [comment]
Nothing big, but just that you do not have to work on #174 
:)

**Comment by yourhead** [comment]
ha.  but that's a good catch. i've not noticed that before. i bet it's there in S2 as well.
