### ISSUE TITLE
Pluskit vs S3 conflict

### ISSUE THREAD

**Issue by DeFliGra** [yourhead/s3#407]
Seems there's a conflict between PlusKit (latest version = 2.9.2.2) & S3 3.b.0011.
I haven't tested with other version of PlusKit and S3.

From the test I've done adding a @import((pagename)) at the bottom of a page will cause an error in the Stacks plugin and – when previewing in RW or previewing in Safari > will cause all images to go missing with a blue question mark.

Moving the @import((pagename) to the top of the page > things seems to work fine.

The pages I've esperienced with is an old site that works fine with latest verison of PlusKit + latest version of S2. I've also done a simple test with a completly new site (stacks page) + PlusKit + @import((pagename)) > with same result as the old site I've tested.

How did I repeat the issue:
Create a new site with a S3 page with some text and images. Add PlusKit. Create a text-stack with the @import((pagename)) at the top of the page. Preview. Result: Things looks fine. // Move it to the bottom of the page. Preview. Result: Images missing & sometimes S3 shows an error message.

Can anyone confirm?

**Comment by DeFliGra** [comment]
Maybe not important... Partial Pages might replace PlusKit fully – if you build your site entirely (or almost) with Stacks !?

**Comment by yourhead** [comment]
irrelevant. S3 should be 100% compatible with S2 files. no exceptions.

**Comment by yourhead** [comment]
i will fix this bug. it's just very very hard. and requires a lot of time. it will likely take me a week or two.

**Comment by alxalxnet** [comment]
I'm experiencing the same issue, but regardless of the position of the @import((pagename)) text-stack.
It looks like it occurs if the page includes more than one @import text-stack. I'm glad that it's being fixed as I have several sites structured with PlusKit. I look forward to the fix!

Thanks for the excellent job on Stacks 3!!

**Comment by alxalxnet** [comment]
Hi there,
I downloaded and installed the latest beta (3.0.0.b16) but I'm still experiencing the same issue.

**Comment by yourhead** [comment]
@alxalxnet - well, it's definitely not the **same** issue -- but perhaps very similar. however without more details, i can't help you out or fix the bug.

the best thing to do would be to simply post your details (crash report -- if that's what you're experiencing) to a new bug. if they are indeed the same, then i can always merge the info later on. thx

**Comment by alxalxnet** [comment]
Thanks! 
I'm not experiencing any crash, just an issue partlly similar to the one described above: a page including more than one @import((page-name)) will cause "an error in the Stacks plugin and – when previewing in RW or previewing in Safari > will cause all images to go missing with a blue question mark."

I can send you a copy of the project via email.

**Comment by yourhead** [comment]
@ alxalxnet - ok, that doesn't have anything to do with this bug. let's take that as a support request. please contact me via Slack (slack.yourhead.com) or our customer support email address.

i'll need a copy of the file and a copy of your RapidWeaver addons folder zipped up.  You can send those in a private message via slack. or share them via dropbox with customer support. whichever works best for you.

**Comment by yourhead** [comment]
issue seems specific importing one pluskit page into another
