### ISSUE TITLE
Instant RW crash with certain stacks since beta11

### ISSUE THREAD

**Issue by ghost** [yourhead/s3#410]
I’ve got a repeatable bug thats been introduced in b11, (tested in b9 and 10) 
If you drag either BWD’s ScrollMate or S4S's HotSpotPro on to a page it will crash RW. 
I’ve tested different themes with the same result. 
Of the 130+ stacks I have these are the only 2 that will crash RW in this manor.

**Comment by spidercrab** [comment]
I tried this with ScrollMate (Foundation 1.52 everything up to date) and RW crashes instantly.  However, RW when restarted locks up with a beach ball and needs a hard reset to restart Mac.  When RW is launched the RW error reporter appears and Mac locks up again needing another hard reset to recover and get RW working again.  This is more a heads up to anyone thinking of checking this and also to highlight that there is still a problem with RW that stops it from recovering from a crash.  I have reported this to Realmac.

**Comment by atavernor** [comment]
@yourhead  I have isolated the problem in this issue.

It is caused when a control is the sole control in a group and is shown and hidden via an enable, or more generally if the contents of a group are all hidden via an enable.

Here is a simple devstack demonstrating the problem
https://cloudup.com/cd486HugZeT

I wondered if this was the case as from the crash log it looked as though there was a NSAutoresizingMaskLayoutContsraint with translatesAutoresizingMaskIntoConstraints set to true and it seemed logical that this may be related to the expansion of a group.   I may have been barking up the wrong tree but at least it lead me to the cause of the crash :)

**Comment by willwood** [comment]
I can replicate this same issue too.

FYI: The free demo version of HotSpotsPro can be downloaded from my website here if you need the real thing to test against: https://stacks4stacks.com/hotspotspro/

I've not had reports from anybody else of this stack or others causing RapidWeaver to crash. I've followed all the API guidelines for control enables and can't see anything wrong with my markup.

With regards to the issue @spidercrab has raised about the RapidWeaver crash reporter getting stuck in an infinite crash loop, I've found this can happen if you try to submit a crash report without providing a comment.

**Comment by atavernor** [comment]
@willwood The problem has only been introduced with b11.  I suspect that is why you have not had any reports of it.

**Comment by yourhead** [comment]
@atavernor - regression introduced when fixing #394. i suspect an off by one error somewhere in enumerating the contents of the groups.

**Comment by yourhead** [comment]
@willwood - yes, brand new. this bug has been in the wild just a hair over 24 hours
