### ISSUE TITLE
CSS code wrapped in 'if edit' conditionals does not auto-update when edited

### ISSUE THREAD

**Issue by willwood** [yourhead/s3#411]
A nice feature in Stacks 3 I'm very pleased to see is the ability for a stack element to automatically update / refresh in edit mode, without needing to manually call-up the Developer window and hit the refresh button.

However I've noticed that for CSS code wrapped inside 'if edit' statements, the styling does not take effect until you manually restart RapidWeaver each time. Add the following to the CSS file of any stack:

```
#%id% {
    background: blue;
    padding: 20px;
}

%[if edit]% 
#%id% {
    background: red;
    padding: 20px;
}
%[endif]%
```

What you would expect is for the stack to immediately gain a red background in edit mode. But actually the background of the stack in edit mode remains unchanged until you restart RapidWeaver.

Obviously this can be (as I found at the weekend) and bit of a PITA for developers working on new or updated stacks and needing to tweak minor things in edit mode! Right now it requires RapidWeaver to be restarted each time. Not sure if this is a bug or an intended feature of S3. I couldn't see it documented anywhere that 'if edit' conditionals are exempt from refreshes.

**Comment by yourhead** [comment]
what version of S3 are you seeing this in... as this is similar to a bug that was fixed in B9

**Comment by willwood** [comment]
3.0.0b11 according to the Info.plist file in Stacks. Bundle version 2773.

**Comment by yourhead** [comment]
ok. thanks. looks like a special case of the old bug i fixed. some caching i'm not clearing. thanks for the good detective work and all the details.

**Comment by yourhead** [comment]
- i built a stack and copied your code from this bug report into an each scoped css template.
- the html has "hello world"
- there is no other css, js, or html in the stack
- i dropped this stack onto a new page in a new project.
- i changing the color red to green.

it behaved as expected, the color edit mode changed to green a couple seconds later.
here is a link to the stack in question so you can see what i see and compare it to what you're doing.

https://dl.dropboxusercontent.com/u/433436/teststack.devstack.zip

if i'm looking at this wrong, or have made some type of error, just let me know and we'll open the bug again. thx

**Comment by willwood** [comment]
I'm still have difficulty with CSS changes made inside 'if edit' conditionals not taking effect until RapidWeaver gets restarted. I've recorded a video here which might hopefully provide a better overview of the issue I'm encountering:
https://dl.dropboxusercontent.com/u/422052/screencasts/Stacks3-ifedit-css-bug.mp4

And here is a download link for my system profile:
https://dl.dropboxusercontent.com/u/422052/MacBook%20Air.spx.zip

I just took your stack exactly as you sent it to me, and changed the background colours. No other modifications or changes to the stack. I've tried leaving RapidWeaver for 30 minutes after making a CSS change, and no update occurs in edit mode to the stack background within that time.

**Comment by yourhead** [comment]
no other users have been able to duplicate the experiment. this seems isolated to a single case.

**Comment by yourhead** [comment]
i'm afraid this seems limited to just your machine. no other developer has been able to replicate this. thus i think this should be handles as a support request unless some new data comes to light.

BTW:  i have sent you questions on slack about this. thx.
