### ISSUE TITLE
Settings not reflected in nested partials

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#414]
1. Partial-A is nested inside Partial-B
2. Change the settings of a stack inside Partial-A
3. Those settings are not reflected in Partial-B until I go to edit Partial-B

**Comment by yourhead** [comment]
i don't see this behavior.
1. created a text stack
2. selected and clicked partial (this is partial B)
3. added a second text stack to the partial
4. selected the second text stack and click partial (this is partial A)
5. clicked back twice to leave all partials
6. add partial A to the page by dragging from the library
7. edit partial A
8. Add a border to partial A
9. click Back

The page now shows the border on both partial A and partial B.

I have also tried editing partial A in other ways (different pages, by editing it inside of another partial, etc.) i have not seen a case where partial B fails to reflect the changes i make.
