### ISSUE TITLE
some users don't see font awesome icons icons loaded in edit mode

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#421]
in particular Moving Box stack which loads its own copy of Font Awesome into edit mode

**Comment by joeworkman** [comment]
MovingBox has an update for S3 that uses Stacks 3 version of Font Awesome.

**Comment by yourhead** [comment]
that was only one concrete example of the problem that extends to multiple stacks. basically any stack that calls FontAwesome is unviewable to this user in S3. however the same stack works as expected in S2.

**Comment by joeworkman** [comment]
Could it be a conflict with loading multiple versions of Font Awesome on the same page? When MovingBox loaded its own FA, it used v4.3.0. Stacks 3 obviously loads v4.4.0

**Comment by yourhead** [comment]
nope.
highly technical and experienced user (Matthais).
10.10.4 (no betas)
Stacks beta 12
New document
New page
Only stack on the page.
i have video proof.

random other things also crossed off:
- Font Awesome is not installed at the system level.
- Rebooting doesn't change anything.
