### ISSUE TITLE
some users see intermittent dropouts of particular icons in the library

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#422]
this seems to only be foundation stacks currently

unconfirmed:  this may be just related to recently updated stacks

**Comment by zeebe** [comment]
I saw this happen today, going from Foundation 1.4.4 to 1.5.5, many of the foundation stacks were missing, a restart of RapidWeaver fixed it for me though. Not sure if this helps, but thought I would report what I saw.

**Comment by yourhead** [comment]
@zeebe -- was it right after an update? like you update, then they're gone...   but as soon as you restart they come back?

**Comment by zeebe** [comment]
Yup, exactly

**Comment by yourhead** [comment]
ok. well that's a good experiment i can try. thanks.

**Comment by yourhead** [comment]
I think I may have found the source of this. I'm going to mark it closed as of beta 13 with about 25% confidence. If anyone sees this bug ongoing, please report here and we will reopen.

If you do see a problem, please run through this list and answer as many questions as you can while the problem is fresh on your screen:
- are there any messages displayed in the OS X Console app when this happens?
- are there any messages displayed in the Stacks Developer console when this happens?
- did it occur after a stack update? (if so, is the missing icon one of the stacks that was updated?)
- does this bug occur to stacks other than Foundation? (if so, which stack?)
- does the missing icons show up in different stacks when scrolling through the list -- or always the same stacks?
- does the behavior change after relaunching RapidWeaver?

**Comment by yourhead** [comment]
confirmed to be a bug in Foundation v1.5.5 and v1.5.6 reported to Joe
