### ISSUE TITLE
%html within conditional problem

### ISSUE THREAD

**Issue by atavernor** [yourhead/s3#43]
If a %html is used within a %if conditional statement then within edit mode the default text is replaced by %2

The indexing of the %html nodes appears to be corrupted as in the following example:

```
%[if %id=title%]%  
        <span>%html="Some Text"% </span> 
%[else]% 
        <span>%html="Some Other Text"%</span> 
%[endif]% 
```

Results in 
%id=title% = true  displays "%2"  in edit mode
%id=title% = false displays "Some Text" in edit mode

With a more complex arrangement of %html declarations, subsequent stacks will jump inside the problem stack in edit mode.

The problem stack works as expected without problems in Stacks 2.

Example stack HeaderTest.stack posted to Slack. Note, this is not a .devstack for easy comparison between Stacks 2 and 3.

The example uses spans around the %html statements but the same behavior occurs regardless of the tag used.

**Comment by yourhead** [comment]
fixed in alpha 3
