### ISSUE TITLE
stack replacement does not flush css caches in edit mode

### ISSUE THREAD

**Issue by bbyrdhouse** [yourhead/s3#440]
Edit:  Nothing to do with if-edit. Nothing to do with updates. Affects:  css-each, css-page, scss-each, and scss-page.

Whenever I have a stack on a page that is ready to receive an update the html that resides inside of an %[if edit]% macro does not get refreshed properly if the stack is already on the page. 
However adding a new instance of the stack to a page the html within the %[if edit]% macro is updated properly. Here is an image that shows the difference:

<img width="798" alt="edits_1_2_update_test" src="https://cloud.githubusercontent.com/assets/7376298/9171609/ae3e2856-3f32-11e5-92aa-b84df01f83c6.png">

I closed out of RW and restarted and re-did the update and got the same result. 
RapidWeaver - Version 6.3.1 (14986)
Stacks - latest version

**Comment by bbyrdhouse** [comment]
Isaiah, 

If you want, I can send you a stack that you can do an update on and you will be able to see this. I ran into it again just now.

**Comment by yourhead** [comment]
so long as the stack is very trivial then yes, please do. if it's like a whole for sale stack with a bunch of other stuff in it -- then no thanks

**Comment by bbyrdhouse** [comment]
Ok ... I will see if I can build a trivial stack and repeat the issue. As it stands, the stack that is already on the page never seems to get the html inside the [if edit]% updated.

**Comment by bbyrdhouse** [comment]
Ok, here is a trivial stack that has an update ready to go. 
http://kulercloud.com/2I2A232F2J0o
1. Drag the stack to your page
2. Check for updates and install the update
3. You will be able to see that though the stack gets updated, parts of it do not.

You can then drag the updated stack from your library to the page to compare the two.

Hope this helps

**Comment by yourhead** [comment]
this stack does not have the "devstack" extension.

**Comment by yourhead** [comment]
sorry, far too complex to be useful in debugging. i appreciate you trying.  :-)
this problem is a needle. it's impossible to find in a haystack this big.
the easiest way to find a needle is to start with the smallest haystack possible.

**Comment by bbyrdhouse** [comment]
Yikes ... I'm not sure how much easier it could get.

**Comment by bbyrdhouse** [comment]
After further investigation, it is actually the css that is contained inside

```
%[if edit]%

%[endif]%
```

that does not get updated in a stack **when that stack is on the page at the time of doing a stack update**.

New instances of the stack that get dragged from the library to the page are ok, it is **only** the stack that was **already** on the page that the css does not get updated.

This is definitely repeatable for me and affects more than one stack.

**Comment by yourhead** [comment]
i'm aware of all those things. thanks gary. appreciate you efforts.

> "I'm not sure how much easier it could get"

here is the entire content of the html template i'm using to test this:

```
outside <br> %[if edit]% inside %[endif]%
```

one line. nothing interesting. no extra hay to hide the needle. pretty much just all needle.

and by doing that, i could see in about 1 minute that it had nothing to do with the html template and i could eliminate this file as a culprit, altogether.

other things i've eliminated:
- it doesn't have anything to do with updates/sparkle/networks
- it doesn't have anything to do with the contents of the plist changing
