### ISSUE TITLE
The @58 icon is still used for the Update UI

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#441]
If I have a stack that does not have the older @50 and @58 icons, no icon will show up inside the update UI. As soon as I add the @58 icon, and recheck for updates it will display the icon. 

I will place Foundation 1.5.7 on our Dropbox share. These will try to update to 1.5.8. You will see the issue.

**Comment by joeworkman** [comment]
The bug...

![screen shot 2015-08-10 at 8 26 09 am](https://cloud.githubusercontent.com/assets/225628/9175442/9f427c0a-3f3a-11e5-8841-2d99411733b2.png)
![screen shot 2015-08-10 at 8 26 18 am](https://cloud.githubusercontent.com/assets/225628/9175443/a0c0d6d0-3f3a-11e5-9c28-a8f21da8d27f.png)

**Comment by joeworkman** [comment]
The fix... 

![screen shot 2015-08-10 at 8 27 27 am](https://cloud.githubusercontent.com/assets/225628/9175457/abc93e14-3f3a-11e5-90ef-72da290c4b3e.png)

**Comment by joeworkman** [comment]
This bug still occurs. If I try to update a stack that does not have the @50 & @58 icons, the update window still show no icon at all.

**Comment by yourhead** [comment]
bugger

**Comment by yourhead** [comment]
for sure this time.
