### ISSUE TITLE
Stacks Says that it has been updated but it doesn't actually update

### ISSUE THREAD

**Issue by bbyrdhouse** [yourhead/s3#450]
I'm currently testing Joe's update app cast script and Stacks tells me that there is an update to a stack (this is good because there actually is an update). When I click on 'install' it looks like it downloads and Stacks tells me that the stack has been updated (installed) but it is actually still the old version.

![Stacks updater](https://cloud.githubusercontent.com/assets/7376298/9277073/77771fc4-426d-11e5-93e7-1adb62589aeb.png)

![Stacks updater fail](https://cloud.githubusercontent.com/assets/7376298/9277078/7f8f6c48-426d-11e5-89fe-d6d4f12ead1f.png)

This is what the console says: 

![Stacks updater console](https://cloud.githubusercontent.com/assets/7376298/9277169/fc231778-426d-11e5-963c-5db82e5bce4b.png)

Please let me know what else I need to provide to help you know if this is a bug.

**Comment by yourhead** [comment]
was this intended to be closed? if so why? no solution was obvious here.

**Comment by bbyrdhouse** [comment]
I closed it because I assumed that the issue has to do with the appcast.php implementation when looking for Stacks API specific updates. 
I removed that part from the script and Stacks can now update fully.

**Comment by yourhead** [comment]
:thumbsup:
