### ISSUE TITLE
library in window mode remains open even after document is closed.

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#456]

**Comment by ghost** [comment]
I can confirm this, steps to reproduce:
Start RW.
New Project, Add Stacks Page.
Library > Window Mode
Close Project via RW Project's traffic lights (without saving)
Library window remains.
Making another app the foreground app will make the Library window disappear but returning focus to RW will make the Library window appear again.

**Comment by ghost** [comment]
In fact you can keep going, make new project, window the library and then closing the project > repeat.
https://infinit.io/_/35UYup2
