### ISSUE TITLE
Stack inspector window loses ability to TAB between fields after the window loses then regains focus

### ISSUE THREAD

**Issue by AnInfiniteNumberofMonkeys** [yourhead/s3#459]

**Comment by yourhead** [comment]
wow. strange bug. an no obvious cause. behavior coming purely from default os x controls.

**Comment by elixirgraphics** [comment]
Not sure if they're related, or if this should be a separate issue, but tabbing between fields in RW 7 is non-existent for some reason. Tabbing forces the value of the field to be updated, but the focus remains on the current field instead of advancing to the next one.
