### ISSUE TITLE
Using delete/backspace key to remove a stack will delete its contents and replace it with the default stack content, but not remove the stack itself.

### ISSUE THREAD

**Issue by NimbleHost** [yourhead/s3#460]
Steps to reproduce:
1. Create a new project
2. Add a single text stack to the page
3. Change the contents of the stack
4. Click somewhere else on the page, so the stack is no longer selected
5. Select the stack by clicking on it
6. Hit the delete or backspace key
7. Changes to the stack's contents are deleted, and replaced with the default lorem ipsum text, but the stack remains on the page

**Comment by NimbleHost** [comment]
This is with beta 15.

**Comment by yourhead** [comment]
this is actually the intended behavior...     but maybe it shouldn't be.    hmmm

**Comment by yourhead** [comment]
the (slightly) modified behavior seems to have become acceptable to most users. however the UI changes for 4.0 will require some re-think -- but i think we'll give that a different bug when it comes up.
