### ISSUE TITLE
@import from one stacks page onto another stacks page will cause one of the two pages to fail to export assets

### ISSUE THREAD

**Issue by alxalxnet** [yourhead/s3#470]
original description of the problem

```
If a Stacks page includes more than one @import text stacks, when I preview or export the page all images appear as broken links (with a blue question mark appearing in place of each image).

I sent you a copy of the Rapid Weaver project file via email (file attachment is: Stacks 3 - Pluskit issue.rw6).
```

i could not duplicate the original description, but i can see something close -- i believe the original description made assumptions as to the cause of the problem.

**Comment by yourhead** [comment]
i did not fix the originally described problem but fixed something similar.  if the original problem does crop up again, we should file that bug separately and reference this one.

the problem fixed was:
when @importing from one stacks page to another, each export called will clear the export folder -- so only the assets associated with the last exported call will actually get exported.  i suspect this means if you had many @imports on one page that only the final one would export images all other pages, including the page being injected with content, will fail to export any assets.
