### ISSUE TITLE
"Global" margin inherits detailed margin after it is reset

### ISSUE THREAD

**Issue by leifottosson** [yourhead/s3#475]
1. Start new project and add a Stacks page.
2. Insert a stack (I tested with the text stack).
3. Set "Layout" detailed margin top to 100 px.
4. Preview.
5. Go back to Edit mode.
6. Change detailed margin to 0 and close the panel with the -.
7. "Global" marin is now set to 100 px.

This does not happen all the times, but I haven't found out exactly what's triggering the bug.

If you don't understand, se movie here: https://infinit.io/_/wjL5jqs

**Comment by yourhead** [comment]
good catch.
thanks.

it looks like the internal value is correct, but the view is not being updated with the correct value.

**Comment by yourhead** [comment]
although i verified this bug in the past. the current beta build no longer displays this behavior. i think i snuck in a fix at some point without updating the status of this bug.
