### ISSUE TITLE
Feature Request: Non Partial Stack within a Partial Stack

### ISSUE THREAD

**Issue by DeFliGra** [yourhead/s3#478]
Partials are a game changer. Amazing feature... so I was thinking.

If it was possible to create a partial stack > add non partial stacks withing the partial stack > then you'd have a MasterPage kind of same way as master pages works in Adobe Indesign.

You'd be able create a master page – all the surrounding layout on all stacks pages – then add non partial stacks > for page specific content... to areas within the partial stack / page.

This way you'd be able to use partial pages as kind of a theme... a master page with an option to change master page elements but at the same time add page specific content (stacks).

I'm just dreaming...

**Comment by yourhead** [comment]
that's exactly what u pinning a stack does. have you watched the video?

**Comment by DeFliGra** [comment]
I’ve watched the video… around 3 o’clock am.After 60 updates.I’ll have another look.Best,DeFliGraDen 28. aug. 2015 kl. 07.10 skrev isaiah notifications@github.com:that's exactly what u pinning a stack does. have you watched the video?—Reply to this email directly or view it on GitHub.
