### ISSUE TITLE
stack that does not work in S3

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#483]
I am putting Scroll.dmg on our share. It contains the stack and a project file. It does not work in S3. I have not debugged this yet. But wanted to file an issue anyways.

**Comment by yourhead** [comment]
no errors, no warnings in the js console.
no obvious templating errors or missing bits.
my wild ass guess is that it has to do with image width/height

**Comment by yourhead** [comment]
closing this as i think there's nothing more to do here.
