### ISSUE TITLE
hidden attribute to settings

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#485]
It could be interesting to be able to add a hidden attribute to settings so that they do not show up inside the settings pane. 

This could be useful if I have an input where I would like to set something but not have users be able to. Or possibly useful in some update situations.

**Comment by yourhead** [comment]
what's the purpose of a variable you can't vary?

**Comment by atavernor** [comment]
I do this with "future features" etc just by setting an enable to a non existent value of a select control. (The select control itself does of course exist)

**Comment by yourhead** [comment]
there is a non zero perchance penalty for each control. 

should probably be weighed carefully against the benefit

**Comment by yourhead** [comment]
"each control" -- yes even the hidden ones.

**Comment by atavernor** [comment]
I don't fill the pList with these - only one or two on the odd occasion. I realise they will still all get processed - just saying there is a way around it.

**Comment by yourhead** [comment]
:thumbsup:
