### ISSUE TITLE
Cannot add stacks to groups in OS 10.9

### ISSUE THREAD

**Issue by girlcarew** [yourhead/s3#489]
Create a new RW document with a Stacks page.
Create a new group using the + sign (it's the only way you can) and give it a name.
Drag and drop a stack from the main library to the icon of the group you just created.

Nothing happens.

**Comment by MrBLK** [comment]
It works for me. I dragged the Text stack into the newly created group, and it shows in there.

**Comment by yourhead** [comment]
@MrBLK - are you running Mac OS X 10.9?

**Comment by MrBLK** [comment]
Sorry, I am running 10.10.5.

**Comment by kryten68** [comment]
Any update on this? Its kinda burning me a little...

**Comment by yourhead** [comment]
@kryten68 - i'd strongly encourage you to stop running 10.9. it will be dropped from Stacks support as soon as is practical.

**Comment by kryten68** [comment]
Hi Isaiah

Thanks. I think it's time for a new MacBook..... 

Regards
Stuart

**Comment by yourhead** [comment]
Every device that can run 10.9 is also 10.11 compatible. Or, well, that's what the apple docs say at least. Maybe not true if you're using a Mackintosh or something I guess.
