### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by girlcarew** [yourhead/s3#490]
---1---
Incident Identifier: 651C17E9-D2C7-403C-AB5E-5FBC96A22810
CrashReporter Key:   TODO
Hardware Model:      MacBookAir4,1
Process:         RapidWeaver 6 [3977]
Path:            /Applications/RapidWeaver 6.app/Contents/MacOS/RapidWeaver 6
Identifier:      com.realmacsoftware.rapidweaver6
Version:         15046
Code Type:       X86-64
Parent Process:  launchd [1]

Date/Time:         2015-09-02 14:45:02 +0000
OS Version:        Mac OS X 10.10.5 (14F27)
Framework Version: 1.0.3
Report Version:    106

Exception Type:  SIGSEGV
Exception Codes: SEGV_NOOP at 0x0
Crashed Thread:  12

Thread 0:
0   libobjc.A.dylib                     0x00007fff9067ed66 _ZL23weak_entry_for_referentP12weak_table_tP11objc_object + 78
1   libobjc.A.dylib                     0x00007fff9069612e weak_read_no_lock + 30
2   libobjc.A.dylib                     0x00007fff90681122 objc_loadWeakRetained + 111
3   YHStacksPlugin                      0x000000010ce099e0 -[YHNode __parent] + 16
4   YHStacksPlugin                      0x000000010cded018 -[YHNode document] + 24
5   YHStacksPlugin                      0x000000010cded030 -[YHNode document] + 48
6   YHStacksPlugin                      0x000000010cded030 -[YHNode document] + 48
7   YHStacksPlugin                      0x000000010cded030 -[YHNode document] + 48
8   YHStacksPlugin                      0x000000010cded030 -[YHNode document] + 48
9   YHStacksPlugin                      0x000000010cdefb12 -[YHNode setupGlobals] + 50
10  YHStacksPlugin                      0x000000010cdefc08 -[YHNode setupGlobals] + 296
11  YHStacksPlugin                      0x000000010cdefc08 -[YHNode setupGlobals] + 296
12  YHStacksPlugin                      0x000000010cdefc08 -[YHNode setupGlobals] + 296
13  YHStacksPlugin                      0x000000010cdefc08 -[YHNode setupGlobals] + 296
14  YHStacksPlugin                      0x000000010cded271 -[YHNode wake] + 225
15  YHStacksPlugin                      0x000000010cded338 -[YHNode wake] + 424
16  YHStacksPlugin                      0x000000010cded338 -[YHNode wake] + 424
17  YHStacksPlugin                      0x000000010cded338 -[YHNode wake] + 424
18  YHStacksPlugin                      0x000000010cded338 -[YHNode wake] + 424
19  YHStacksPlugin                      0x000000010cded338 -[YHNode wake] + 424
20  YHStacksPlugin                      0x000000010cded338 -[YHNode wake] + 424
21  YHStacksPlugin                      0x000000010ce99390 -[YHPartial wake] + 48
22  YHStacksPlugin                      0x000000010ce83382 -[YHPartialsLibrary addPartial:] + 98
23  YHStacksPlugin                      0x000000010ce8ac22 -[YHPartialNode findPartialsWithDocument:] + 82
24  YHStacksPlugin                      0x000000010cdee4ff -[YHNode findPartialsWithDocument:] + 255
25  YHStacksPlugin                      0x000000010ce8e637 -[YHStacksPage findPartials] + 167
26  YHStacksPlugin                      0x000000010ce8e16d -[YHStacksPage loadNib] + 653
27  libdispatch.dylib                   0x00007fff93433323 _dispatch_call_block_and_release + 12
28  libdispatch.dylib                   0x00007fff9342ec13 _dispatch_client_callout + 8
29  libdispatch.dylib                   0x00007fff9343acbf _dispatch_main_queue_callback_4CF + 861
30  com.apple.CoreFoundation            0x00007fff91a943f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
31  com.apple.CoreFoundation            0x00007fff91a4f68f __CFRunLoopRun + 2159
32  com.apple.CoreFoundation            0x00007fff91a4ebd8 CFRunLoopRunSpecific + 296
33  com.apple.HIToolbox                 0x00007fff9572156f RunCurrentEventLoopInMode + 235
34  com.apple.HIToolbox                 0x00007fff957212ea ReceiveNextEventCommon + 431
35  com.apple.HIToolbox                 0x00007fff9572112b _BlockUntilNextEventMatchingListInModeWithFilter + 71
36  com.apple.AppKit                    0x00007fff970cd8ab _DPSNextEvent + 978
37  com.apple.AppKit                    0x00007fff970cce58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
38  com.apple.AppKit                    0x00007fff970c2af3 -[NSApplication run] + 594
39  com.apple.AppKit                    0x00007fff9703f244 NSApplicationMain + 1832
40  libdyld.dylib                       0x00007fff9181a5c9 start + 1

Thread 1:
0   libsystem_kernel.dylib              0x00007fff8d508232 kevent64 + 10
1   libdispatch.dylib                   0x00007fff93431a6a _dispatch_mgr_init + 0

Thread 2:
0   libsystem_kernel.dylib              0x00007fff8d5024de mach_msg_trap + 10
1   com.apple.CoreFoundation            0x00007fff91a4feb4 **CFRunLoopServiceMachPort + 212
2   com.apple.CoreFoundation            0x00007fff91a4f37b __CFRunLoopRun + 1371
3   com.apple.CoreFoundation            0x00007fff91a4ebd8 CFRunLoopRunSpecific + 296
4   com.apple.CFNetwork                 0x00007fff8e957420 +[NSURLConnection _resourceLoadLoop:] + 434
5   com.apple.Foundation                0x00007fff97cb4e92 __NSThread__main** + 1345
6   libsystem_pthread.dylib             0x00007fff9938005a _pthread_body + 131
7   libsystem_pthread.dylib             0x00007fff9937ffd7 _pthread_body + 0
8   libsystem_pthread.dylib             0x00007fff9937d3ed thread_start + 13

Thread 3:
0   libsystem_kernel.dylib              0x00007fff8d5024de mach_msg_trap + 10
1   com.apple.CoreFoundation            0x00007fff91a4feb4 __CFRunLoopServiceMachPort + 212
2   com.apple.CoreFoundation            0x00007fff91a4f37b __CFRunLoopRun + 1371
3   com.apple.CoreFoundation            0x00007fff91a4ebd8 CFRunLoopRunSpecific + 296
4   com.apple.AppKit                    0x00007fff9719556b _NSEventThread + 137
5   libsystem_pthread.dylib             0x00007fff9938005a _pthread_body + 131
6   libsystem_pthread.dylib             0x00007fff9937ffd7 _pthread_body + 0
7   libsystem_pthread.dylib             0x00007fff9937d3ed thread_start + 13

Thread 4:
0   libsystem_kernel.dylib              0x00007fff8d5073fa __select + 10
1   libsystem_pthread.dylib             0x00007fff9938005a _pthread_body + 131
2   libsystem_pthread.dylib             0x00007fff9937ffd7 _pthread_body + 0
3   libsystem_pthread.dylib             0x00007fff9937d3ed thread_start + 13

Thread 5:
0   libsystem_kernel.dylib              0x00007fff8d507136 __psynch_cvwait + 10
1   libc++.1.dylib                      0x00007fff95f38c95 _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   com.apple.JavaScriptCore            0x00007fff99da1544 _ZN3JSC14BlockAllocator22blockFreeingThreadMainEv + 228
3   com.apple.JavaScriptCore            0x00007fff99d96cff _ZN3WTFL19wtfThreadEntryPointEPv + 15
4   libsystem_pthread.dylib             0x00007fff9938005a _pthread_body + 131
5   libsystem_pthread.dylib             0x00007fff9937ffd7 _pthread_body + 0
6   libsystem_pthread.dylib             0x00007fff9937d3ed thread_start + 13

Thread 6:
0   libsystem_kernel.dylib              0x00007fff8d507136 __psynch_cvwait + 10
1   libc++.1.dylib                      0x00007fff95f38c95 _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   com.apple.JavaScriptCore            0x00007fff99da1adb _ZN3JSC8GCThread16waitForNextPhaseEv + 171
3   com.apple.JavaScriptCore            0x00007fff99da1938 _ZN3JSC8GCThread12gcThreadMainEv + 88
4   com.apple.JavaScriptCore            0x00007fff99d96cff _ZN3WTFL19wtfThreadEntryPointEPv + 15
5   libsystem_pthread.dylib             0x00007fff9938005a _pthread_body + 131
6   libsystem_pthread.dylib             0x00007fff9937ffd7 _pthread_body + 0
7   libsystem_pthread.dylib             0x00007fff9937d3ed thread_start + 13

Thread 7:
0   libsystem_kernel.dylib              0x00007fff8d507136 __psynch_cvwait + 10
1   libc++.1.dylib                      0x00007fff95f38c95 _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   com.apple.JavaScriptCore            0x00007fff99da1adb _ZN3JSC8GCThread16waitForNextPhaseEv + 171
3   com.apple.JavaScriptCore            0x00007fff99da1938 _ZN3JSC8GCThread12gcThreadMainEv + 88
4   com.apple.JavaScriptCore            0x00007fff99d96cff _ZN3WTFL19wtfThreadEntryPointEPv + 15
5   libsystem_pthread.dylib             0x00007fff9938005a _pthread_body + 131
6   libsystem_pthread.dylib             0x00007fff9937ffd7 _pthread_body + 0
7   libsystem_pthread.dylib             0x00007fff9937d3ed thread_start + 13

Thread 8:
0   libsystem_kernel.dylib              0x00007fff8d507136 __psynch_cvwait + 10
1   libc++.1.dylib                      0x00007fff95f38c95 _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   com.apple.JavaScriptCore            0x00007fff99da1adb _ZN3JSC8GCThread16waitForNextPhaseEv + 171
3   com.apple.JavaScriptCore            0x00007fff99da1938 _ZN3JSC8GCThread12gcThreadMainEv + 88
4   com.apple.JavaScriptCore            0x00007fff99d96cff _ZN3WTFL19wtfThreadEntryPointEPv + 15
5   libsystem_pthread.dylib             0x00007fff9938005a _pthread_body + 131
6   libsystem_pthread.dylib             0x00007fff9937ffd7 _pthread_body + 0
7   libsystem_pthread.dylib             0x00007fff9937d3ed thread_start + 13

Thread 9:
0   libsystem_kernel.dylib              0x00007fff8d50794a __workq_kernreturn + 10
1   libsystem_pthread.dylib             0x00007fff9937d3dd start_wqthread + 13

Thread 10:
0   libsystem_kernel.dylib              0x00007fff8d507136 **psynch_cvwait + 10
1   com.apple.Foundation                0x00007fff97d5bd6e -[__NSOperationInternal _waitUntilFinished:] + 131
2   com.apple.Foundation                0x00007fff97d68ff9 -[NSOperationQueue addOperations:waitUntilFinished:] + 192
3   com.realmacsoftware.RWKit           0x00000001079455a7 +[RWPage createWithSandwich:pageIndex:document:missingPages:] + 1047
4   com.realmacsoftware.rapidweaver6    0x0000000107549ed0 0x1074bf000 + 569040
5   com.realmacsoftware.rapidweaver6    0x00000001074f919d 0x1074bf000 + 237981
6   com.realmacsoftware.rapidweaver6    0x000000010754a142 0x1074bf000 + 569666
7   com.realmacsoftware.rapidweaver6    0x00000001074f919d 0x1074bf000 + 237981
8   com.realmacsoftware.rapidweaver6    0x0000000107549ca4 0x1074bf000 + 568484
9   com.realmacsoftware.rapidweaver6    0x00000001075496b6 0x1074bf000 + 566966
10  com.realmacsoftware.rapidweaver6    0x00000001075492b0 0x1074bf000 + 565936
11  com.realmacsoftware.rapidweaver6    0x00000001075126ff 0x1074bf000 + 341759
12  com.realmacsoftware.rapidweaver6    0x0000000107512a8f 0x1074bf000 + 342671
13  com.realmacsoftware.rapidweaver6    0x00000001075008e2 0x1074bf000 + 268514
14  com.apple.AppKit                    0x00007fff97200b15 -[NSDocument _initWithContentsOfURL:ofType:error:] + 171
15  com.apple.AppKit                    0x00007fff972009f5 -[NSDocument initWithContentsOfURL:ofType:error:] + 230
16  com.apple.AppKit                    0x00007fff97383278 -[NSDocumentController makeDocumentWithContentsOfURL:ofType:error:] + 627
17  com.apple.AppKit                    0x00007fff975ba9c9 __97-[NSDocumentController makeDocumentWithContentsOfURL:alternateContents:ofType:completionHandler:]_block_invoke + 85
18  com.apple.Foundation                0x00007fff97cd08b8 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK** + 7
19  com.apple.Foundation                0x00007fff97cd0685 -[NSBlockOperation main] + 97
20  com.apple.Foundation                0x00007fff97ccfb3c -[__NSOperationInternal _start:] + 653
21  com.apple.Foundation                0x00007fff97ccf613 __NSOQSchedule_f + 184
22  libdispatch.dylib                   0x00007fff9342ec13 _dispatch_client_callout + 8
23  libdispatch.dylib                   0x00007fff93432365 _dispatch_queue_drain + 1100
24  libdispatch.dylib                   0x00007fff93433ecc _dispatch_queue_invoke + 202
25  libdispatch.dylib                   0x00007fff934316b7 _dispatch_root_queue_drain + 463
26  libdispatch.dylib                   0x00007fff9343ffe4 _dispatch_worker_thread3 + 91
27  libsystem_pthread.dylib             0x00007fff9937fa9d _pthread_wqthread + 729
28  libsystem_pthread.dylib             0x00007fff9937d3dd start_wqthread + 13

Thread 11:
0   libsystem_kernel.dylib              0x00007fff8d50748a **semwait_signal + 10
1   libsystem_c.dylib                   0x00007fff9192be44 usleep + 54
2   com.apple.AppKit                    0x00007fff97343e43 -[NSUIHeartBeat _heartBeatThread:] + 2376
3   com.apple.Foundation                0x00007fff97cb4e92 __NSThread__main** + 1345
4   libsystem_pthread.dylib             0x00007fff9938005a _pthread_body + 131
5   libsystem_pthread.dylib             0x00007fff9937ffd7 _pthread_body + 0
6   libsystem_pthread.dylib             0x00007fff9937d3ed thread_start + 13

Thread 12 Crashed:
0   libobjc.A.dylib                     0x00007fff9067e44f objc_release + 15
1   YHStacksPlugin                      0x000000010cd966bb -[YHLibraryItemsController clearItems] + 43
2   YHStacksPlugin                      0x000000010cd9695d -[YHLibraryItemsController flush] + 45
3   YHStacksPlugin                      0x000000010ce46b59 -[YHLibraryViewController partialsChanged:] + 57
4   com.apple.CoreFoundation            0x00007fff91afd45c **CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER** + 12
5   com.apple.CoreFoundation            0x00007fff919ed634 _CFXNotificationPost + 3140
6   com.apple.Foundation                0x00007fff97c7daa1 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
7   YHStacksPlugin                      0x000000010ce83638 -[YHPartialsLibrary broadcastPartialsChanged] + 216
8   libdispatch.dylib                   0x00007fff93433323 _dispatch_call_block_and_release + 12
9   libdispatch.dylib                   0x00007fff9342ec13 _dispatch_client_callout + 8
10  libdispatch.dylib                   0x00007fff9343188f _dispatch_root_queue_drain + 935
11  libdispatch.dylib                   0x00007fff9343ffe4 _dispatch_worker_thread3 + 91
12  libsystem_pthread.dylib             0x00007fff9937fa9d _pthread_wqthread + 729
13  libsystem_pthread.dylib             0x00007fff9937d3dd start_wqthread + 13

Thread 13:
0   libsystem_kernel.dylib              0x00007fff8d50794a __workq_kernreturn + 10
1   libsystem_pthread.dylib             0x00007fff9937d3dd start_wqthread + 13

Thread 12 crashed with X86-64 Thread State:
   rip: 0x00007fff9067e44f    rbp: 0x000000011b610a10    rsp: 0x000000011b6109f8    rax: 0xbadde47ebfd9bead 
   rbx: 0x000060800059f070    rcx: 0x0000000000000004    rdx: 0x00007f8d59746ed0    rdi: 0x000060800059f070 
   rsi: 0x0000000000001000     r8: 0x0000000000000fff     r9: 0x000060800059f070    r10: 0x00007f8d59746ed0 
   r11: 0x000000000000000a    r12: 0x00006080002e0a10    r13: 0x000000000011144b    r14: 0x00007f8d58a9fd50 
   r15: 0x00007fff906760c0 rflags: 0x0000000000010246     cs: 0x000000000000002b     fs: 0x0000000000000000 
    gs: 0x0000000000000000

**Comment by yourhead** [comment]
it looks like this is some combination of a change to partial combined with a the library change (like a stack was updated).  i've tried to duplicate -- it's not obvious how to make this happen or if it was just a fluke.
