### ISSUE TITLE
updated jQuery library

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#5]

**Comment by jrondorf** [comment]
- Which jQuery version will be included in S3?
- Feature request: Option to use in addition to the Google CDN a local version of jQuery supplied by S3.
  - When working offline with no internet connection (plain), you have to change the generated Stacks page manually to point to a local version of jQuery in order having the generated HTML and Stacks to work.
  - Creating an intranet site w/o access to the internet

**Comment by jrondorf** [comment]
@yourhead 
Do you already made up your mind which exact jQuery version will be referenced in s3, e.g. 1.11.x or 2.1.x ?
I would like to start testing my Stacks with this jQuery version already now.
Thanks!

**Comment by yourhead** [comment]
s3 will support a range of jQuery versions. stacks will use the most current jQuery version that is allowed by all stacks on the page.
when stacks on the page require versions that don't overlap the user will receive an error message.

**Comment by yourhead** [comment]
a couple more details:

the current mechanisms of defining "javascriptlib" (etc) will be deprecated in favor of a single "libraries" array to define the required libraries. this will include at least:  jQuery, MooTools, jQueryUI, and Font Awesome.  jQuery will be the only library in which you can define a range of versions. other libraries will come with the single latest version as they've always done.

**the first few betas of Stacks will lock the version of jQuery to the very latest:  2.1.3.  The hope is to encourage stack developers to do a bit of updating and discover incompatibilities.**
