### ISSUE TITLE
Serious Crash  .... Logs included

### ISSUE THREAD

**Issue by bbyrdhouse** [yourhead/s3#506]
I've just experienced what Stacks called a "Serious" crash. It presented me with the following logs:

Stacks Error
Stacks v3.0.2 (2865) - Fri, 02 Oct 2015 08:15:30 -0500

Exception: NSInvalidArgumentException
Reason: **\* -[__NSArrayM insertObject:atIndex:]: object cannot be nil

(
    0   CoreFoundation                      0x00007fff880bcbd2 __exceptionPreprocess + 178
    1   libobjc.A.dylib                     0x00007fff8c95ddd4 objc_exception_throw + 48
    2   CoreFoundation                      0x00007fff87fd3370 checkForCloseTag + 0
    3   Stacks                              0x0000000107eb82ed YHSliceKeyReport + 7053
    4   Stacks                              0x0000000107e62b6a CGPatternWithCGImage2x + 191242
    5   Stacks                              0x0000000107e62abc CGPatternWithCGImage2x + 191068
    6   Stacks                              0x0000000107e62abc CGPatternWithCGImage2x + 191068
    7   Stacks                              0x0000000107e62abc CGPatternWithCGImage2x + 191068
    8   Stacks                              0x0000000107ef1b14 YHStacksPageInit + 23540
    9   Stacks                              0x0000000107ef2087 YHStacksPageInit + 24935
    10  Stacks                              0x0000000107e20f14 YHStacksPluginReport + 5140
    11  RWKit                               0x0000000102e8a25a -[RWExporter _exportPage:toPath:inRoot:usingName:] + 4442
    12  RWKit                               0x0000000102e910c7 -[RWExporter _exportPage:toPath:inRoot:usingName:includingChildren:] + 215
    13  RWKit                               0x0000000102e91bb0 -[RWExporter exportPage:toPath:inRoot:usingName:includingChildren:] + 160
    14  RapidWeaver 6                       0x0000000102a43b41 -[MyDocument(PageExport) com_rwrp_startPageExportAsync:] + 257
    15  RapidWeaver 6                       0x0000000102a443a2 __108-[MyDocument(PageExport) exportPage:toDirectory:inRoot:usingName:includingChildren:mode:onBackgroundThread:]_block_invoke + 34
    16  RMCoreConcurrency                   0x0000000102d45a9e -[RMPromiseOperation _invokeBlock] + 65
    17  RMCoreConcurrency                   0x0000000102d45a48 -[RMPromiseOperation main] + 27
    18  Foundation                          0x00007fff899731c6 -[__NSOperationInternal _start:] + 654
    19  Foundation                          0x00007fff8996f1b0 __NSOQSchedule_f + 194
    20  libdispatch.dylib                   0x00007fff93985453 _dispatch_client_callout + 8
    21  libdispatch.dylib                   0x00007fff9398a083 _dispatch_queue_drain + 754
    22  libdispatch.dylib                   0x00007fff939906c9 _dispatch_queue_invoke + 549
    23  libdispatch.dylib                   0x00007fff93988d9b _dispatch_root_queue_drain + 538
    24  libdispatch.dylib                   0x00007fff93988b48 _dispatch_worker_thread3 + 91
    25  libsystem_pthread.dylib             0x00007fff8f4564f2 _pthread_wqthread + 1129
    26  libsystem_pthread.dylib             0x00007fff8f454375 start_wqthread + 13
)

The error happened while in the very early stage of development of a new stack.

Hope this helps.

**Comment by yourhead** [comment]
Is this crash repeatable? Or did it just happen once?

**Comment by bbyrdhouse** [comment]
It hasn't happened again ... I don't think it is repeatable because I can't get it to happen again.

**Comment by yourhead** [comment]
unfortunately there is not really enough to go on here. there is a chance that i've already fixed this in the upcoming build (i've fixed about 5 crashers -- all quite rare)
