### ISSUE TITLE
%baseURL% does not work in Edit Mode

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#507]
Would it be possible to have %baseURL% actually get resolved inside Edit Mode?

Example, it would be nice if this worked inside edit mode. 

<img class="" src="%baseURL%/cms-data/image/banner.jpg" alt="My Image">

**Comment by yourhead** [comment]
this currently works, mostly.

there is no notification when the user edits the base url value. so after editing the value shown will be stale until the next time the stack content is re-rendered.

preview mode will always work since preview and export never use cached values
