### ISSUE TITLE
Output corrupted when using %id% tag exactly five times.

### ISSUE THREAD

**Issue by robertotremonti** [yourhead/s3#509]
Here's attached a stack that contains a small workaround at line `4`.
Basically I've added the `%id%` tag once more just to avoid output corruption.
If you remove the line, output will be corrupted both in Preview and in Export/Publish.

https://www.dropbox.com/s/pdetjf6jeyfib4m/RapidCartProProduct.devstack.zip?dl=1

**Comment by yourhead** [comment]
I've built a simple stack that add a text %id% five times. it works as expected.
the provided example is interesting -- but far too complex to be helpful.

i don't doubt that there is a problem somewhere. however i don't think this bug describes that bug or provides any information that might help in finding that bug. so i'm glowing to close this bug.
my guess is this bug likely has something to do with php syntax interacting with stacks template syntax.

i'll be on the lookout for anything that might be related. if you do have some specific info or an cut your example down to size we can create a new bug to describe that problem or re-open this one if it really does have something to do with the number 5.

**Comment by robertotremonti** [comment]
Yes, as said, I guess the problem is in using `%id%` in numerous occurrences inside PHP code like

```
$rcCart%id%->page
```

It doesn't seem to work well with PHP `->` operator, probably a mix of operators and other chars that breaks regexp parsing.
Leaving a sixth occurence as a comment fixes it and doesn't hurt anyone, so I'll keep the code as it is.
Thank you.

**Comment by yourhead** [comment]
just provide some steps to show me how to make it happen.

**Comment by robertotremonti** [comment]
Remove line `4` from my code (the commented one) and it won't work.

**Comment by yourhead** [comment]
what code? in slack?

**Comment by robertotremonti** [comment]
`product.php` file inside the stack you can download from link in first message.

https://www.dropbox.com/s/pdetjf6jeyfib4m/RapidCartProProduct.devstack.zip?dl=1

Line 4:

```
//%id% fix to avoid output corruption
```

Sorry for not having mentioned it previously.

**Comment by yourhead** [comment]
as i already said:

> the provided example is interesting -- but far too complex to be helpful.

steps or gtfo.  :-P

joking.  ;-)

but serious:  in order to find this bug, i'll have to reduce your stack to just a line or two.  to reverse engineering your stack enough to do that will take me **hours**.
but with your understanding of the stack and your understanding of the bug -- it would take you minutes.

are a few minutes to you more than me wasting hours?
