### ISSUE TITLE
File paths + Relative to Website Address

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#510]
When a project is set to `Relative to Website Address`, then the URL that is inserted for library paths is missing a slash after http. 

I have noticed this with CSS libraries. However, the behavior could be with other files added by Stacks. 

Stacks is inserting

```
<link rel="stylesheet" type="text/css" media="all" href="http:/sandbox.joeworkman.net/rw_common/plugins/stacks/foundation.css" />
``

 Instead of 

```

<link rel="stylesheet" type="text/css" media="all" href="http://sandbox.joeworkman.net/rw_common/plugins/stacks/foundation.css" />

```

Note the first only has one slash after the http, instead of two. 
```

**Comment by yourhead** [comment]
i think this one snuck into the last release even though it wasn't in the change list
