### ISSUE TITLE
%stackVersion% (et al) is broken in page scoped templates

### ISSUE THREAD

**Issue by marathia** [yourhead/s3#512]
In page scoped templates stack-info (e.g. %stackVersion% ) is exported from the page node rather than the stack itself.

**Comment by jrondorf** [comment]
Works for me in CSS files, e.g.:
/\* %stackTitle% %stackVersion% */

**Comment by marathia** [comment]
Update: not fully tested, but this happens in combination with

`<key>scope</key>`
`<string>page</string>`

Updated the title accordingly.

**Comment by yourhead** [comment]
I've tested this in the current beta builds and it "just works" for me.  I'm not sure if it was a bug in your stack or perhaps an old bug in some previous version of stacks -- but it doesn't seem to be a problem anymore.

If you still see this error please include a simple test stack that shows this behavior.

**Comment by marathia** [comment]
For your reference, I attached a stack I stripped as much as possible. In my version of Stacks (3.0.2 [2865]) `%stackVersion%` shows in each.html, each.css and each.js but not in page.css and page.js

[versionTest.stack.zip](https://github.com/yourhead/s3/files/65341/versionTest.stack.zip)

**Comment by yourhead** [comment]
![pasted_image_12_17_15__11_50_am](https://cloud.githubusercontent.com/assets/98634/11877366/7159860a-a4b4-11e5-90bc-1926579b7fc0.png)

i dropped in your stack, opened the dev console and this is what i see -- it looks to me to be working as expected.

perhaps you can give me some more details about how you are testing this.  and perhaps you should use the same version as me:  3.0.3 beta 4 available on http://slack.yourhead.com

**Comment by marathia** [comment]
It happens when previewing a page with the stack in a browser, or exporting/publishing that page. The latest beta makes no difference.

![schermafbeelding 2015-12-17 om 21 14 31](https://cloud.githubusercontent.com/assets/5559822/11880854/73317ab0-a503-11e5-9719-8cf2670aa8e6.PNG)

**Comment by yourhead** [comment]
that screenshot seems to show the expected behavior. the version string is 1.0.0 and that's what i see in your screenshot.
what am i missing?

**Comment by marathia** [comment]
The stack version in page.css:

![schermafbeelding 2015-12-17 om 21 14 31](https://cloud.githubusercontent.com/assets/5559822/11881101/ee270e3c-a504-11e5-8943-9f41c87a5920.PNG)

**Comment by yourhead** [comment]
OK. got it. and now i see the problem. thanks.
