### ISSUE TITLE
Feature Request: Warning when opening a page with a stack, which is not installed any more

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#513]
When uninstalling Stack Addons (either from the library or in finder) and you open a project where this Stack Addon is still referenced, you are getting an empty **Template** Stack.
It would be nice having a warning message when opening this page in order to prevent publishing problems.

**Comment by kalkul** [comment]
This is a good one. I have been experiencing that quite a lot lately as I removed many non-responsive stacks

**Comment by yourhead** [comment]
This requires some significant UI invention. As with all things UI related, it's moving to S4

**Comment by yourhead** [comment]
splitting this bug out into three parts:

- #700 - the look/feedback/ui of the stack in-situ when it is missing.
- #701 - an API to let stack developers customize the feedback of missing stacks.
- #702 - an alert notifying users of missing stacks

the first two are going in 3.5. the last one i'm hoping is unnecessary as there are already too many alerts. however if it still seems necessary then we can add it in 4.0

**Comment by yourhead** [comment]
Closing this bug in favor of the other three.
