### ISSUE TITLE
exported stack js should be compressed and comment free

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#530]
Stacks places a lot of comments inside the JS files. Most of the comments look like notes to developers and are the same for every stack in the file. I know its a small win but removing the comments could help save a few KB per page.

**Comment by yourhead** [comment]
i'm splitting this out into two separate bugs:
- #549 : comments. the HTML generation prefs for comments should probably affect the comments in the generated JS as well. this bug so i'll tackle it asap.
- #551 : whitespace. same as comments.
- #550 : compress. this is very difficult as JS compression is not an exact science and is generally handled via command-line tools -- something that's difficult for a native plugin to accomplish.  for this reason i have to put this one in the "someday" category.

**Comment by yourhead** [comment]
closing this as it's now covered by the other bugs/features
