### ISSUE TITLE
multiline text controls do not finish editing and save edits in some cases

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#532]
When the settings pane is a window, the multi-8 settings will not save text typed into them. The text always reverts back to what it used to be set as. 

If the settings are docked or in a popover, everything works as expected. 

Video: https://infinit.io/_/HuXKFVY

**Comment by yourhead** [comment]
should probably call finish editing whenever the info panel is updating to ensure that things without a field editor store changes before being released

**Comment by yourhead** [comment]
enabling the field editor on the text views fixed it. yeah! didn't even think the would work.
