### ISSUE TITLE
regexkit bug is causing replacement failures

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#533]
I know that we have seen this bug in the past. I thought that it was resolved but I could be wrong. Anyways it has cropped up again in one of my Total CMS stacks. TotalToggle.stack is the offending stack. Its a fairy simple stack so thought it was a good use case. 

Project file: https://infinit.io/_/GBWnf8n
Total CMS: http://jwurl.net/1Qfpkel

In the project file you will see 2 instances of the Toggle stack. One works, the other is broken and you see the Stacks API calls inside edit mode. 

To break it, you simply need to add any 12 characters into the CMS ID setting.

**Comment by yourhead** [comment]
it actually has nothing to do with length. it's a bug in there regex library. unfortunately when i fix it in one place it seems to squish out of another.

if you have a simple way to demonstrate this i can probably fix and release it today. however in the current form this will take me a at least a couple days to condense into something workable and will miss the window for the current bug release i'm hoping to push out today.

**Comment by yourhead** [comment]
i've added changes that fixes one variant of this issue.  however i have a strong suspicion that this bug will continue to rear up in odd places.  please file SIMPLE examples that reproduce this behavior whenever possible if they do occur in other places.

huge examples that rely on large stacks with dozens of templates replacements are counterproductive and just waste time.
