### ISSUE TITLE
custom line height + centered text

### ISSUE THREAD

**Issue by girlcarew** [yourhead/s3#535]
1. Create a text stack.
2. Enter some text and center it.
3. Choose "Custom" Line Spacing.
4. Edit the text.
   You can see the box around the text has shifted left, making it off center.

**Comment by yourhead** [comment]
i cannot duplicate this using the given steps in the current stacks build.  either this was fixed at some earlier time, or requires something else to make it happen.

**Comment by yourhead** [comment]
i'm guessing this is related to #486 and should be marked as a duplicate.
