### ISSUE TITLE
Macro for %pageName% 

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#536]
For getting the name that the user set the page name to: index.html, index.php, page2.php, etc.

**Comment by barchard** [comment]
:+1:

**Comment by yourhead** [comment]
as this changes the API (requiring a version update) i'm putting this one in the v3.1 bin. but seems like a no-brainer.

**Comment by joeworkman** [comment]
Did this make it into v3.1?

**Comment by yourhead** [comment]
in beta 3

**Comment by yourhead** [comment]
page "name" was a little generic. and there are several different names and titles that are interesting for templates.  so i've split this into a few features:  #690, #691, #692, #693
