### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by themacguru** [yourhead/s3#537]
When I click the update button to open the update window - the result says All stacks are up to date. If I click Check For Updates, then updates will be found. My suggestions is:
1. Don't have a result preloaded upon open
2. Have it run on open

**Comment by halsteadb** [comment]
As I understand it from previous conversations with Isaiah, Stacks auto checks for updates on first launch of RapidWeaver per day and flags the number of updates available in the Update button. I may have misunderstood his explanation.

My request would be that it replaces "All Stacks are up to date" with _Last checked: date/Time_ if what I understand to be true.
