### ISSUE TITLE
Deleting stacks from page results in parts left behind on export

### ISSUE THREAD

**Issue by halsteadb** [yourhead/s3#538]
I have a projects based on Foundations by Joe Workman, in that Project came a reference to his Post Office stack (which I do not own and hence showed in RW 6.3.7 as a Template). I delete the template from the stacks page, I mark all pages and resources as changed, publish or export site and resource files for the Post Office stack are still exported/published.

Expected behaviour: if you delete a stack from the page, it's dependancies should be removed as well if not required elsewhere, which in this case they are not..

Current work-a-round: instead of leaving a stack drop zone on the page (where Post Office was) in question, replace it with another stack and the issue resolves. No export of non-required stack resources (PHP files, css, etc).

**Comment by yourhead** [comment]
i'm afraid i cannot duplicate the behavior that you're seeing. when i delete a stack from a page it does not publish any of the resources of the deleted stack.

if you can create a simplified version of this behavior with built-in stacks it would make it much easier to track down.

**Comment by halsteadb** [comment]
Just for clarity, you are correct, there were 2 mailers on the site I was working on and I didn't notice the second.
