### ISSUE TITLE
Date settings not directly passable via JS Date object

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#539]
The current date settings output the following format: `2005-10-15T12:00:00PDT`

If you pass this string to a JS Date object, its seen as an invalid date format. 

`var date = new Date('2005-10-15T12:00:00PDT');`

In order for JS to be able to parse the date sting, it should not have the timezone. Seems very odd as you are providing the ISO 8601 date format. This seems like a JS/browser issue but may be something that you could address. 

For now I will just strip the timezone myself. Its not for an extremely time sensitive setting any how.

**Comment by yourhead** [comment]
i'm of two minds about this:  on one hand i'd like to support the dominant format -- which is likely ISO 8601 JS format.  however i don't really want to get in the habit of providing many different date formats. currently JS and Moment is easily betters any of the native Cocoa libraries for date handling and formatting.
