### ISSUE TITLE
Ability to not require time for date settings

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#540]
There are times that I don't care about the time for a date setting. It would be nice the time was not displayed in the settings pane. Its fine if the output defaults to 12:00:00 AM in this case.

**Comment by joeworkman** [comment]
Never mind... there is a date plist type. Should have thought about that first.

**Comment by joeworkman** [comment]
Might want to update the docs though...

**Comment by joeworkman** [comment]
My last 2 comments were meant for a different issue. Just noticed that...

**Comment by yourhead** [comment]
in beta 8
