### ISSUE TITLE
HTML Templates: pageHeadBelow causes page scopes to be ignored

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#553]
If you have an HTML template with a scope set to `pageHeadBelow` all HTML templates scoped to `page`

I created a modified version of the templates demo from Github. It did not have any page scoped templates, so I added them. 
1. Download and install https://infinit.io/_/sJprZHn 
2. Add stack to a new page.
3. Notice that the page scope template does not show in preview. 
4. Edit the stack and remove the pageHeadBelow  scoped HTML template form the plist.
5. Preview the page again and notice that the page scoped HTML templates is not displayed.

**Comment by yourhead** [comment]
This bug appears to have been fixed at some point. When using pageHeadAbove/Below and pageBodyAbove/Below things behave as expected. They display in edit and preview and replace templates as expected.
