### ISSUE TITLE
Built-in Image stack not respecting round corners with/out border

### ISSUE THREAD

**Issue by halsteadb** [yourhead/s3#554]
Using the included image stack, it is not generating the round corners as defined in the stack settings.

**Comment by yourhead** [comment]
corner rounding is purely a function of the borders, not the content in the stack. so the current behavior is the intended one. 

also: this is a long standing built in behavior of Stacks. at this point changing that behavior would imply changing tens of thousands of web sites -- which is obviously not an option.  iow: long standing behaviors have enough inertia that they cannot easily be changed even if that change is desirable.
