### ISSUE TITLE
Padding added to the site without any reason

### ISSUE THREAD

**Issue by leifottosson** [yourhead/s3#556]
This is a weird one. Suddenly I have a 15px padding around my whole site.

http://leifottosson.se

It's set in the Stacks Page settings in the Page Inspector but I'm 100% sure I have not set it.
I had this strange error when you can't open the Page Inspector when using a Stacks page (even on my 27"). I fixed it by quitting RW, starting it again and creating a new page with a Styled Text page. Then I could open the Page Inspector again. Quitting and starting again and I can open the Page Inspector using a Stacks page. I made a few small changes and published all pages and there it was, a 15px padding. Boom!

**Comment by joeworkman** [comment]
This is not a bug. You probably have 15px padding added to the Stacks page. Click on the Stacks background in edit mode and look at the settings.

**Comment by leifottosson** [comment]
That's exactly right Joe, only that I'm 100% sure I have not set it. Somehow it got there all by itself. I forgot to mention it but I've had this behavior once before but didn't report it since I thought I was my "fault".

**Comment by leifottosson** [comment]
My guess is that is has something to do with the bug when you can't open the Page Inspector when using a Stacks page. Happens from time to time for me.

**Comment by joeworkman** [comment]
Got a link to the project file?

**Comment by leifottosson** [comment]
Project file here: https://infinit.io/_/qunDQiC

**Comment by joeworkman** [comment]
Just as I suspected.... 
![screen shot 2016-03-03 at 5 35 35 am](https://cloud.githubusercontent.com/assets/225628/13495849/d5df17f0-e101-11e5-8bb4-7f3026932f42.jpg)

**Comment by leifottosson** [comment]
Yes, I'm very well aware of that setting, Joe. But I did _not_ set it. That's the bug. I can easily change it back to 0 but the bug is that it gets there somehow by itself when opening the project.

**Comment by joeworkman** [comment]
That is going to be a hard bug to prove unless you can reproduce the steps to make it happen.

**Comment by leifottosson** [comment]
As I wrote earlier I _think_ it has something to do with the well known bug that you sometimes can't open the Page Inspector when using a Stacks page. Closing RW and starting it again with a Styled Text page makes it possible to open the Page Inspector again. Closing RW again and opening a project with Stacks pages and you can open the Page Inspector again. This is what I did and after republishing all pages I had this padding. It will probably be hard to prove since it looks like it's depending on another bug to happen first.

**Comment by yourhead** [comment]
I have no doubt this is a bug. Or that you've experienced it. So in that sense this is a good bug report and it's good that we've logged this, in case more info about this is discovered that might help us track this down.

However there isn't much info that might help me find or even repeat the bug. In short: there's not really anything for me to do other than hope I bump into this myself.

A bug without a clear course of action always gets closed.
