### ISSUE TITLE
stacks meta tag name field is not valid html5

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#557]

**Comment by joeworkman** [comment]
Yes, it is... https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

**Comment by yourhead** [comment]
note the details on the name attribute. it has specific allowed values. it's not free-form the way that we're using it.  and some overzealous seo tools flag it as a problem.

**Comment by joeworkman** [comment]
Food for thought on this... 

Twitter uses the name attribute for their twitter cards: https://dev.twitter.com/cards/types/summary

Apparently, there is a growing list of acceptable name values. You can submit your own as well... This makes it seem rather wide open. https://wiki.whatwg.org/wiki/MetaExtensions

Open Graph instead uses the property attribute: http://ogp.me

Another thought is that you could use the title attribute which is global for all elements.

**Comment by yourhead** [comment]
while greg's seo tool continues to be widely used i'll probably have to live by the rigorous spec or be forced to deal with the consequences tons of generating errors.

this has nothing to do with practicality or the usefulness of these tags.

if you can get greg to interpret the meta tag specification in a more practical contemporary manner, then i'll be happy to follow suit.  but currently i'm generating a ton of support from that tool and these tags. i need to do something to stem the bleeding.

**Comment by barchard** [comment]
Do you mind posting an example html tag? Thanks.

**Comment by joeworkman** [comment]
```
<meta class="stacks3 stack version" id="com.joeworkman.stacks.totalcms.text" name="Text" content="1.2.0">
```

**Comment by barchard** [comment]
A quick glance over the code, the only meta name that should be checked are robots, googlebot, msnbot and bingbot. I'll check tonight that the Regex matching is working.

**Comment by yourhead** [comment]
Well, it looks like whatever tool folks are using for validating/optimizing their seo it's probably not Greg's. So we're even more hosed. It might be that this is just being flagged by a google validation tool or something similar.

Seems to me that until it's de rigueur for validation tools to accept non-standard metas we're going to have to standardize or suffer the consequences. 

Standardization seems like the least painful path to me.

**Comment by joeworkman** [comment]
Ask the people who sent in tickets what they used. I bet that they used an HTML4 validation tool. Or the one from W3C.

**Comment by yourhead** [comment]
i can ask, but unless it's someone i know, there's little chance of us having an effect. the one variable we have control over here is the meta tags we write.

**Comment by yourhead** [comment]
i think my recommendations to customers who demand strict meta-tag spec compliance is just to disable these tags via prefs.
