### ISSUE TITLE
Hiding a stack marks page as dirty

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#583]
If you hide a stack via the toolbar button, it will mark the page as dirty. Not a huge deal, just something that I noticed.

**Comment by yourhead** [comment]
I don't think there's any easy way around this.  I have to make the page as needing to be saved. Whenever that happens the page will also be marked as dirty and needing upload.

However if the content itself doesn't change, then the RW publishing cache should recognize that and not actually upload anything.
