### ISSUE TITLE
Math controls default to rounding with no `round` key specified

### ISSUE THREAD

**Issue by atavernor** [yourhead/s3#585]
Without a `round` key set to `false` math controls apply rounding when operating a division. In order to return a non integer it now seems mandatory to add a `round` `false` key value pair into the math control.

This appears to be a change in the default behavior as controls that previously returned decimal values no longer do so without explicitly specifying that they should not be rounded.

[Math.devstack.zip](https://github.com/yourhead/s3/files/273685/Math.devstack.zip)

**Comment by atavernor** [comment]
With the devstack above:
**The Number 1 control has no rounding key in its assocaited math control which is set to / 100**
Enter any number greater than 50 in to the number 1 control -> the math control returns 1
Enter any number less than 50 in to the number 1 control -> the math control returns 0

**The Number 2 control has `round` `false` specified in its associated math control**
Entering any number into number to produces the expected result of `number 2 / 100` to 2DP

**Comment by yourhead** [comment]
This is the desired (and even documented!!!) behavior of the math control. It behaves this way for historical reasons. I'm afraid there is so much logic built upon this that there is precisely zero chance that this will ever change.  I know it's a bit odd -- it's one of those very old bits of legacy API that is lurking deep in there from before we really knew how much the Stacks API would be used.
