### ISSUE TITLE
Each scoped template for <head>

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#587]
It would be very nice to have an each scoped template that could go into <head>

**Comment by yourhead** [comment]
sorry, rejected. 

it would be too easy to build something that would add a line to the header for every trivial text stack. and some dev would do that having only tested it with 2 stacks on his page and some user would use it and put 500 stacks on the page and then they would be angry that stacks had a 500-line long header.

**Comment by joeworkman** [comment]
Those devs would put stuff 500x in the `<body>` then. What is the difference if its in `<head>` vs `<body>`?
