### ISSUE TITLE
padding differences (input, multi-n)

### ISSUE THREAD

**Issue by marathia** [yourhead/s3#590]
It's only a cosmetic thing, but my OCD is playing up here…

The padding of the `input` control is different than that of `multi-2`,  `multi-4` and  `multi-8`:

![screen shot 2016-05-27 om 12 34 33](https://cloud.githubusercontent.com/assets/5559822/15604321/68072e94-2408-11e6-96da-688e01fb8dcf.png)

The `multi-2` is also little too wide, causing horizontal scroll:

![screen shot 2016-05-27 om 12 40 20](https://cloud.githubusercontent.com/assets/5559822/15604346/926c53c6-2408-11e6-8e4c-cd4a55a35ebd.png)

**Comment by yourhead** [comment]
Checked. This is just the difference between "Single Line Mode" begin enabled on the field and not.

In other words: this is the expected behavior of macOS.
