### ISSUE TITLE
opacity resets to 100% when selecting another color control

### ISSUE THREAD

**Issue by marathia** [yourhead/s3#593]
I have two color controls (Color 1 and Color 2). The first has `<key>allowsOpacity</key> <false/>`; the second `<key>allowsOpacity</key> <true/>`. 

When setting Color 2 to any color with an opacity <100 and clicking in the color well of Color 1, the opacity of Color 2 resets to 100%.

See attached example stack: [opacityTest.stack.zip](https://github.com/yourhead/s3/files/287873/opacityTest.stack.zip)

**Comment by yourhead** [comment]
in beta 4
