### ISSUE TITLE
Info window's Alt Tag is empty, but S3 adds a default to the published page 

### ISSUE THREAD

**Issue by barchard** [yourhead/s3#594]
It seems that, by default, Stacks adds an Alt Tag to an image. This default tag, however, doesn't appear in the Info pane. I would expect the Alt Tag input field to match what is published by Stacks?

[penny.zip](https://github.com/yourhead/s3/files/290015/penny.zip)
![screen shot 2016-05-30 at 3 36 11 pm](https://cloud.githubusercontent.com/assets/17622/15657190/acda5674-267c-11e6-8692-255eec430778.png)
![screen shot 2016-05-30 at 3 36 31 pm](https://cloud.githubusercontent.com/assets/17622/15657191/afd62ea2-267c-11e6-8847-4f3e2fcb6edc.png)

**Comment by yourhead** [comment]
why?
the default alt property is computer gibberish that's generated to satisfy the valid HTML requirements. it's not human readable and has no informational value to users. why would gibberish be more beneficial than blank?

**Comment by barchard** [comment]
for accuracy and consistency? input = output?

**Comment by yourhead** [comment]
exposing unnecessary implementation detail is questionable accurate, definitely not consistent (nb: I also don't show the final output image name), and guaranteed confusing.

Sorry, I think it's more useful as is. 

If there were some reason for the user to want that info then I'd agree with you, but I can't think of one.
