### ISSUE TITLE
Localize Date Format

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#595]
Europeans are putting in their data format into the settings and not getting the expected results. Is there a way to allow localized input but always out the the same date format?

**Comment by yourhead** [comment]
It's a default date/time control. It should be localized for the machine its running on.
You'll need to provide a concrete example of what fails for me to be able to do anything here.

**Comment by jrondorf** [comment]
I have some kind of the same problem.

My date definition:

```
<dict>
	<key>id</key>
	<string>date</string>
	<key>type</key>
	<string>date</string>
	<key>title</key>
	<string>Date</string>
</dict>
```

Gives me a correct current date + time in the stack settings.

But the HTML template is empty.
```
%id=date%
```

I have to change the date (or the time) inside the stack settings so that the HTML template is getting a date value at all.

**Comment by yabdab** [comment]
I see same thing.
