### ISSUE TITLE
Feature Request: Colour control output variant

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#600]
## Feature request

**Variant output from colour control**

`%id=colourControl -shade%`

Would output a string “dark” or “light” based upon the luminance of the colour. Anything in the lower half of the luminance  scale is “dark” any thing in the higher half of the luminance  scale is “light”.

**Use Case:**
I often use javascript to determine this from a colour value to save on user settings, where a single colour choice really determines that other colours in the stack must be darker or lighter to contrast with the users choice, and there really is no need to ask the user to pick these other colours.

**Simple Example:**

```
<style>
    p{color: %id=colourControl%;}
    %[if %("%id=colourControl -shade%" == "dark")%]%
        /* do everything needed to suit a dark colour choice */
        .background{background:#fff;}
    %[else]%
        /* do everything needed to suit a light colour choice */
        .background{background:#000;}
    %[endif]%
</style>

<div class=“background”>
    <p>Some text here</p>
</div>
```

**Comment by joeworkman** [comment]
Why don't you just use the color math?

**Comment by doobox** [comment]
@joeworkman I can't see how you could possibly determine if the value of a colour control is on the light side or on the dark side with the current colour math. Pretty sure that is impossible. Where talking edit mode here. I can do this without a problem in javascript.

**Comment by yourhead** [comment]
i think this is too app specific. cost very high, but would only be useful in a few areas. seems like JS is a better tool here.
