### ISSUE TITLE
Textarea control

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#61]
It would be nice to have the ability to have a textarea control for settings. If you did not want to add a new _textarea_ control type, maybe simply adding a height option to the existing input type could work as well. This could be nice so that existing settings could be retrofitted with the height option while keeping existing stacks fully functional.

**Comment by yourhead** [comment]
the big roadblock to adding a text area is having a control that has a variable height depending on its value -- that's currently just too costly to performance.

but having specific fixed heights (two-rows, three-rows, etc.) is something that could be doable.

**Comment by yourhead** [comment]
i'll add a few fixed sized smallish text area controls
