### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by bbyrdhouse** [yourhead/s3#611]
Not sure if this is the place for this info but here it is.

**Using RW Version**:  7.1.0 (18121b)
**Stacks 3 Version: 3.2.01** (Bundle version 2997)

The following error report came up after a RW crash aand I did send in the crash report but I never know if those actually get to you.

===BEGIN===
Stacks Error 
Stacks v3.2.01 (2997) - Tue, 09 Aug 2016 09:50:21 -0500

Exception: NSRangeException
Reason: Cannot remove an observer <YHLibraryViewController 0x7fee78320db0> for the key path "stacksToolbarMode" from <NSUserDefaults 0x7fee7370ed40> because it is not registered as an observer.

(
    0   CoreFoundation                      0x00007fff8b24c4f2 **exceptionPreprocess + 178
    1   libobjc.A.dylib                     0x00007fff896fd73c objc_exception_throw + 48
    2   CoreFoundation                      0x00007fff8b2b34bd +[NSException raise:format:] + 205
    3   Foundation                          0x00007fff8c957786 -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 504
    4   Foundation                          0x00007fff8c957533 -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 108
    5   Stacks                              0x000000010764261d YHStackIDLabelClass + 66925
    6   AppKit                              0x00007fff845239a9 -[NSViewController release] + 133
    7   Stacks                              0x0000000107620fce CGPatternWithCGImage2x + 334062
    8   Stacks                              0x000000010761c147 CGPatternWithCGImage2x + 313959
    9   Stacks                              0x000000010762fd37 YHSyncRunOnMainQueue + 46599
    10  Stacks                              0x00000001075bd076 YHStacksPluginReport + 10646
    11  RapidWeaver 7                       0x0000000100355535 -[RWDocument(SandwichLoading) _actuallyLoadFromSandwichAtLocation:error:] + 1301
    12  RapidWeaver 7                       0x0000000100354ff0 -[RWDocument(SandwichLoading) loadFromSandwichAtLocation:error:] + 80
    13  RapidWeaver 7                       0x0000000100312021 -[RWLoadingProjectWindowController loadDocument:atURL:error:] + 193
    14  RapidWeaver 7                       0x0000000100312875 +[RWLoadingProjectWindowController loadDocument:atURL:error:] + 85
    15  RapidWeaver 7                       0x00000001002ff9ce -[MyDocument readFromURL:ofType:error:] + 142
    16  AppKit                              0x00007fff849edde7 -[NSDocument _initForURL:withContentsOfURL:ofType:error:] + 184
    17  AppKit                              0x00007fff849ee013 -[NSDocument initForURL:withContentsOfURL:ofType:error:] + 324
    18  AppKit                              0x00007fff84a318f4 -[NSDocumentController makeDocumentForURL:withContentsOfURL:ofType:error:] + 405
    19  AppKit                              0x00007fff84a30ca0 __104-[NSDocumentController makeDocumentForURL:withContentsOfURL:alternateContents:ofType:completionHandler:]_block_invoke + 77
    20  Foundation                          0x00007fff8c93f8d7 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK** + 7
    21  Foundation                          0x00007fff8c93f595 -[NSBlockOperation main] + 100
    22  Foundation                          0x00007fff8c93dc7a -[__NSOperationInternal _start:] + 654
    23  Foundation                          0x00007fff8c939c64 __NSOQSchedule_f + 194
    24  libdispatch.dylib                   0x00007fff89f2a40b _dispatch_client_callout + 8
    25  libdispatch.dylib                   0x00007fff89f2f03b _dispatch_queue_drain + 754
    26  libdispatch.dylib                   0x00007fff89f35707 _dispatch_queue_invoke + 549
    27  libdispatch.dylib                   0x00007fff89f2dd53 _dispatch_root_queue_drain + 538
    28  libdispatch.dylib                   0x00007fff89f2db00 _dispatch_worker_thread3 + 91
    29  libsystem_pthread.dylib             0x00007fff93ec34de _pthread_wqthread + 1129
    30  libsystem_pthread.dylib             0x00007fff93ec1341 start_wqthread + 13
)

**Comment by yourhead** [comment]
1. No, I don't get those crash reports. (or rarely do)
2. This is a great place to put this.
3. Can you tell me what the last thing is that you did when this happened?

Were you opening a file?
Any other detail about what you were doing would be helpful. Thanks.

**Comment by bbyrdhouse** [comment]
I had opened RW7 (the new dev version 7.1.0 (18121b)) and clicked to open the Stacks library and it took about 15-20 seconds for the library to open, which was wierd because it usually opens right away. 
After the Stacks library opened RW just went into the spinning beachball mode for a while and I did a Force Quit on it.
I resarted RW and the Stacks error reporter came up.

That is really all I had going on or did.

**Comment by yourhead** [comment]
OK. That's perfect info.

And...  I assume this was a one-time thing?  Or does it happen sometimes? Or every time?

**Comment by bbyrdhouse** [comment]
Sorry for the late reply, I got distracted with other stuff. So far it has only happened once.

**Comment by yourhead** [comment]
:thumbsup: -- i've added what i believe should fix this problem -- so i'm going to mark it as closed when i release the developer beta today.  if you see a similar crash please let me know or just reopen this bug. 

thx for the help
