### ISSUE TITLE
drag and drop from the stacks library to create a copy of that item to the dropped location in the Finder.

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#614]

**Comment by joeworkman** [comment]
related to #601 ?

**Comment by yourhead** [comment]
i know this was requisition from a user, but it just seems so strange that i'm going to have to close it.

i think the "normal" way of doing this would be to "show item in finder" then use the finder to make a duplicate.  having other apps make duplicates of unseen things within the finder seems, while feasible, kind of weird.
