### ISSUE TITLE
content not saved if RW quit while editing a stack

### ISSUE THREAD

**Issue by girlcarew** [yourhead/s3#619]
Open RW.
Go to a stacks page (or create one and add a text stack).

Add content to the stack but do not exit the stack (stay as if you are still editing).

Quit RW (Cmd-Q).

The new content is not saved.

**Comment by yourhead** [comment]
this is a sort of UX nightmare.  the reality is that the Editing Mode should be document modal -- forcing the user to finish editing this content before doing anything else that changes the document in any way.

What should happen:
Save should be disabled and NSBeep when attempted.  Close/Quit should "review changed documents" before quitting. With autosave enabled Close/Quit should be disabled.

Those things (things that are very much related to the document delegate) are likely outside of the scope of a rapid weaver plugin without an API change or a lot of swizzling magic.

That leaves our options at:
1. remove the modal behave entirely from the UI.
   pro: it would really fix this problem
   con: it would be a huge change and it's not clear that there's another editing UI that's feasible.
2. always ignore partial edits (this is the current behavior in RW 7+)
   pro: none that i can think of.
   con: data loss. user confusion. bad bad bad.
3. save partial edits when quitting, but not when saving (this the current behavior in RW 6)
   pro: no data loss unless there's a crash. a bit of the best of both worlds
   con: not a very predictable behavior -- which seems ill-advised for saving
4. always save partial edits (planned new behavior for all versions)
   pro: no data loss. very predictable. unlikely to cause confusion.
   con: odd to be saving text that might be canceled out of.
