### ISSUE TITLE
selected stack isn't always shown when Inspector opens

### ISSUE THREAD

**Issue by girlcarew** [yourhead/s3#622]
1. Have a stack on a long page.
2. Click the info button on the bottom most stack.
3. The stack moves off screen when the edit window resizes (after showing the Inspector), so you can't see the stack that the Inspector is showing the info for.

**Comment by yourhead** [comment]
after trying this, i'm no longer convinced this is the right thing to do.  but I have made changes to the selection scroll to the current selected stack. i think this is at least a little better.  (see bug: #621)
