### ISSUE TITLE
Renaming page to php

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#625]
When I add a stack to the page that requires PHP, Stacks does not seem to be able to change the page extension until you leave that page or close/reopen the file. 

I know there is a lot of trickery here. But it does not seem to work as well in RW7.1. 

I tend to set my default extension to PHP on all projects. I am working on a fresh project file this time. It is possible that its behaved like this for some time.

**Comment by yourhead** [comment]
since i haven't changed anything there in forever and the API there is really very trivial and RW 7.1 did change some stuff there very recently -- i'm going to say that this is probably a RW issue and you should file it with those guys.

**Comment by yourhead** [comment]
if they push back we can reopen it here.
