### ISSUE TITLE
Vanilla stack with no div wrappers

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#626]
I currently use the `inline` feature in order to get a stack without a div wrapper. However, this causes the stack in edit mode to look like a child stack (grey background, white border).

This styling is understandable for child stack. However, I would like to have the ability to have an inline stack that is styled like a vanilla stack in edit mode.

**Comment by yourhead** [comment]
i'm punting on this:
- it's hard
- you've already worked around it (sneaky bastard) by restyling bare stacks
- i kind of like that this is possible but extremely difficult. i definitely don't think this is something that should be easy for every developer of every skill level.

perhaps in the future we can make it easy -- but i think, at least for now -- things are probably ok.
