### ISSUE TITLE
%slice -addType dividers

### ISSUE THREAD

**Issue by DeFliGra** [yourhead/s3#627]
Creating menus in Filemaker we can use a hyphen '-' to display a divider. Could be nice having this option when adding stacks directly from a stack with -addType... 

%slice -addTypes="stack,-,com.url.something..."

Just for the overview...

**Comment by yourhead** [comment]
great idea. thanks.

**Comment by joeworkman** [comment]
Not sure is this could be possible for select controls as well. Sometimes I add in fake entries like `--- General ---` in order to categorize the settings.

**Comment by yourhead** [comment]
it should really be part of any generated menu

**Comment by yourhead** [comment]
in beta 9

you can add the value a single dash, just as @DeFliGra suggested (and which is the standard cocoa and MacOS pre-OSX way of doing it too).

NB:  also now works in "select" controls
