### ISSUE TITLE
Move version info to a meta tag

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#628]
It would be super useful if the actual vision of the Stacks plugin was published somewhere with in the HTML, CSS or JS. 

I have had many customers still running Stacks 3.0.0b3 and have never updated. I would absolutely love it if I could have a place to look in order to verify the version of Stacks being used on the page.

**Comment by yourhead** [comment]
This is available now, but customers can disable it if they want.

![pasted_image_9_9_16__1_25_pm](https://cloud.githubusercontent.com/assets/98634/18398109/dc0dd0a6-7690-11e6-97a3-2ea3f66d09cc.png)

With "Comments in HTML" enabled it will be the the first comment in the body content:

![pasted_image_9_9_16__1_27_pm](https://cloud.githubusercontent.com/assets/98634/18398188/2e709022-7691-11e6-8f9f-9469d421cb56.png)

**Comment by joeworkman** [comment]
Why not make this a meta tag? Enabling comments spews a lot of comments onto the page. The version is the one thing that is useful. Its not a stretch since the meta tags already include version information anyways.

**Comment by yourhead** [comment]
ok

**Comment by yourhead** [comment]
ok, it will now appear as a meta tag as well as a comment. since RW is already using the "generator" name i'm going with the little-used "formatter"

```
<meta name="formatter" content="Stacks v3.5.0 (4012)">
```

**Comment by yourhead** [comment]
in beta 9
