### ISSUE TITLE
Add a class to a link

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#631]
It would be awesome if a class could be added to a link generated by the settings. 

The link tool is nice because users can add whatever custom attributes that they want and they get added to the generated link. 

However, it would be nice to ensure that a link has a specific class added to it on top of the attributes that the customer adds. Sometimes frameworks or libraries require that the class be added to the link itself. Therefore, trying to target the link through a parent element is not possible. 

Note: the customer could add a class attribute to the link tool. Therefore, in this case, it would be great if the class to be appended to the classes that the customer added.

**Comment by yourhead** [comment]
ok. just to clarify:
- would the class be specified by you? or by the customer?
- would there be any UI for this? or would this be entirely driven by the API?
- at what point in the API would you want this? (e.g.: as part of the plist for a link control?)

BTW:  there is a remote chance that S4 will have its own link-box UI. the current one limits a lot of things i'd like to add -- and isn't very integrated into stacks. it would be great to improve that. that's in the far off future, but maybe it would be good if features like this one were in sync with that eventuality.

**Comment by joeworkman** [comment]
- Since the customer can add classes via the link tool, I would like to provide my own static classes to add. 
- I do not envision any UI (see next bullet)
- I would say keeping it simply by adding a `linkClass` key into the plist or something like that.

**Comment by yourhead** [comment]
:thumbsup:

**Comment by yourhead** [comment]
in beta 10
docs:  http://api.yourhead.com/templates/link/
