### ISSUE TITLE
Partials add extra set of stacks div wrappers

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#639]
It would be great if content with partials rendered exactly the same as if the content were added directly to that page. Right now, an extra set of stacks wrapper divs are added around the content. I am fine with this being there in edit mode for the UI, but on export, it would be awesome if they were not there. 

The reason is that I have a few stacks that apply styles to the immediate children divs inside the stacks. When partials are used, this breaks everything.

**Comment by yourhead** [comment]
i think this is a good idea in general, but i'm worried that it may already be too late.  there are thousands of partials already in existence now.  if i change their behavior today it could potentially have a very dramatic impact on behavior to all those existing projects.

**Comment by yourhead** [comment]
gave it a quick try. and it even breaks my test files. once we release a structure to the public it's very difficult to change. maybe we can attempt to make it opt-in somehow -- or let existing files opt-out. but for now i'm calling it.
