### ISSUE TITLE
Stack padding control sub titles disappear

### ISSUE THREAD

**Issue by atavernor** [yourhead/s3#670]
I've only seem this happen one and have not been able to reproduce it but it seems others are seeing it as per this 
[RM Forum thread](https://forums.realmacsoftware.com/t/very-random-rw-or-stacks-bug/11856)

For me, it happened only after the update to RW 7.2.2. 
Changing the focus to a different stack and then back again restored the subtitles.

Sorry I have no more specific information as I just ignored it as a glitch at the time and have never seen it since.

**Comment by atavernor** [comment]
Update on this:
I have had it happen again this morning. Using RW 7.2.2. 

Once the problem has occurred it happens with all stacks and all projects:  
- open a new project (any theme - appears to be theme agnostic)
- add a Stacks Text stack
- click the `+` detail button to reveal detailed padding
- the padding number-4 control has no subtitles displayed
(Note the subsequent controls do attempt to slide down to make space but only `wobble` a little)

Restarting RW fixes the problem.

I have still failed to pin down a reproducible course of events trigger this behavior - sorry not much help.

**Comment by yourhead** [comment]
yes, i started seeing this about an update or two ago. i suspect i'm going to have git bisect to track it down. i don't recall making changes to this behavior, but clearly something is confused there.

**Comment by yourhead** [comment]
this seems to have come on suddenly -- and then disappear -- as i no longer see it in Stacks 3.2.7 betas.

to my knowledge there was no changes i've made that affected this.  but i'm going to close this for now as it seems to have gone away.  

if you do see it (especially in the 3.2.7 +) please re-open this bug.
