### ISSUE TITLE
Media can be added to slice regardless of allowedTypes

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#672]
If I have a %slice% that has specific allowedTypes defined, I can still drag and drop an image from the Stacks (media) library and a default image stack will get created inside that slice. This should not be allowed. 

If I move that image stack out of the slice, I will not be allowed to put it back inside though. That is expected.

**Comment by joeworkman** [comment]
This bit me again today. My Email stacks only allow other Email stacks to be added inside of them. However, a customer was able to drag and drop images directly into the Email Column stack. Its easy for me to spot but I figured that I would nudge since you are on a rampage adding features. I understand this is an edge case...

**Comment by yourhead** [comment]
dup #174

this isn't a hard fix, just very risky. it's existed like this so long that i worry that changing it will catch some stacks by surprise that have relied on this side-effect.

**Comment by yourhead** [comment]
closing this one because it's a duplicate
