### ISSUE TITLE
Date element not correctly supplying current date

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#675]
My date definition:

```
<dict>
	<key>id</key>
	<string>date</string>
	<key>type</key>
	<string>date</string>
	<key>title</key>
	<string>Date</string>
</dict>
```

Gives me a correct *current* date + time in the date element inside the stack settings.

But the HTML template is empty. This is returning in above case an empty string.
```
%id=date%
```

I have to change the date (or the time) inside date element in the stack settings so that the HTML template is getting a date + time value.

**Comment by joeworkman** [comment]
I used it in a stack last week and it was working for me. However, I was using the value in a JS template.

**Comment by jrondorf** [comment]
@joeworkman How does your plist entry therefore look like in detail? With above, it doesn't work in html or js templates.
When dropping the stack to the page, it shows the correct date inside the stack settings, but not in the template:

![2017-02-27_08-39-42](https://cloud.githubusercontent.com/assets/2099795/23352608/9523d2ee-fcc8-11e6-9b69-02bd0731d5d9.png)

![2017-02-27_08-39-58](https://cloud.githubusercontent.com/assets/2099795/23352616/9af0fa4e-fcc8-11e6-9b23-2d4abe573648.png)

When you click once "up" in the stack settings, or change a number there, then the correct value will be pasted into the template:

![2017-02-27_08-43-11](https://cloud.githubusercontent.com/assets/2099795/23352662/d37cc834-fcc8-11e6-8854-992074535078.png)

![2017-02-27_08-40-28](https://cloud.githubusercontent.com/assets/2099795/23352620/a14f7028-fcc8-11e6-84c3-e751fe88ee52.png)

**Comment by yourhead** [comment]
fixed in beta 4

also:  that was so much more difficult than you can imagine.  😉

**Comment by jrondorf** [comment]
I guess. I'll retest in b4 and honor it accordingly 😝
