### ISSUE TITLE
Setting subtitles disappear

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#677]
The subtitles added to settings periodically disappear. There does not seem to be a rhyme or reason to it. Adding a new stack to the page or reopening the page seems to fix it most times.

**Comment by yourhead** [comment]
I've seen this in the past, I'd like to fix, but can no longer make it happen. Do you still see this? If so, do you know how to make it happen? Or on what stacks/controls/etc it's most susceptible?

**Comment by joeworkman** [comment]
Yes. It still happens. There should be subtitles below the very last color set. 
![screen shot 2017-06-15 at 10 02 44 am](https://user-images.githubusercontent.com/225628/27192910-e2dd3816-51b1-11e7-8ea1-109c58caa1a6.jpg)

**Comment by yourhead** [comment]
OK, that verified existence, but without some more info about this I think it will remain unfixed.

**Comment by joeworkman** [comment]
I sent you a download for the email stacks. However, I do not know the situation when the subtitles go away. Its working this morning. I am sure by the end of today, I will see it happen again. Is there anything that I can look at once I see that it does happen?

**Comment by yourhead** [comment]
Does it happen on any specific control?  Does it happen when the window is in a specific mode? Does it happen inside a partial? 

Just...   well...   ANY info at this point would be helpful.

I saw this, maybe six months ago, and thought that I had fixed it. I definitely made a change that fixed it for me. Now I never see this problem anymore.

I know other people do see it, but have precisely zero info about when/why/how and really don't even know where to begin to look.

**Comment by joeworkman** [comment]
I have seen it happen on multiple different controls. At least multi-colors and multi-numbers. I pretty much always work in the same view: sidebar panel, not floating.

**Comment by yourhead** [comment]
I have refactored all the code associated with this. I think there is a reasonable chance that I've eliminated the bug in that refactor. I'm going to close this bug with the idea of reopening it if/when the bug shows up in future versions.

In other words, if you see the bug in Stacks 3.5 beta 2 (or later) please provide details, reopen, or open a new bug. thx.
