### ISSUE TITLE
Unpinned Content removed when unpacking a partial

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#679]
If you have a partial with unpinned content, that content gets removed when the partial gets unpacked. I would expect that content to remain in place after the partial was unpacked. 

[PartialUnpin.rw.zip](https://github.com/yourhead/s3/files/883086/PartialUnpin.rw.zip)

1. Open Project file. 
2. Unpack the 2 Column partial. 
3. Text stacks are gone.

**Comment by yourhead** [comment]
in beta 2
