### ISSUE TITLE
Font Awesome CDN loading old version

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#681]
When Font Awesome is loaded from the CDN (via Stack preferences), its still loading v4.3.0 instead of v4.7.0. 

Here is the CDN URL for 4.7: 

```
https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
```

@elixirgraphics mentions this in #663

**Comment by yourhead** [comment]
fixed in the next beta
