### ISSUE TITLE
Use Namespacing for YHStacksUpdate class

### ISSUE THREAD

**Issue by barchard** [yourhead/s3#685]
Namespacing is the hotness. E.g.,

```
<?php
    namespace YourHead;
    use YourHead;

    class StacksUpdate { /* ... */ }
```

then..

```
    use YourHead;
   $updater = StacksUpdate();
```

or

```
   $updater = \YourHead\StacksUpdate();
```

**Comment by yourhead** [comment]
If you'd like to submit pull requests, please do. But I'm afraid the examples are probably going to stick to very basic php unless I have more time to dedicate to them.
