### ISSUE TITLE
HTML templates with scope "page" are omitted

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#688]
In previous versions a compatibility shim was added to inject the template:

html::page

into 

html::pageHeadBlow

this only occurs if there is no other pageHeadBelow template.

this shim was accidentally removed

**Comment by joeworkman** [comment]
Shouldn't this map to `pageBodyAbove`? I am pretty sure that page scoped templates were not inserted into `<head>` before.

**Comment by yourhead** [comment]
fixed in beta 3

**Comment by yourhead** [comment]
> Shouldn't this map to pageBodyAbove? I am pretty sure that page scoped templates were not inserted into <head> before.

Pretty sure that they did go in the head before. I triple checked. Both the code path and the behavior of prior versions.

But you can certainly move things to the body with those other scopes like pageBodyAbove and pageBodyBelow

**Comment by joeworkman** [comment]
OK. I double checked and I migrated the ones that I was thinking of to use the newer page scopes.
