### ISSUE TITLE
new preprocessor macros can collide with old-style macros in special cases

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#694]
with constructions like the following:
```
%[endif]%%[if edit]%%[if whatever]%
```

the middle `if edit` is interpreted as a new-style macro even though it is really an old-style macro

**Comment by yourhead** [comment]
will require modifying the new macro format.

let's see, how 'bout:   `%%[[if edit]]%%`

this is still pretty easy to replace automatically from either the old-style or the (now defunct) new-style

**Comment by jrondorf** [comment]
What about using something like

%[if edit_mode]%, so using another word I stead of "edit"

**Comment by yourhead** [comment]
@jrondorf - that wouldn't actually help as it would still be confused with the more generic conditionals like  `%[if true]%`

I think the proposed doubling should work very well.

**Comment by yourhead** [comment]
fixed in beta 3
