### ISSUE TITLE
Stacks elements updater lost icon preview in 3.5b10

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#710]
Updates of different stack from different developers lost the icon preview in stacks updater.

Example:

![2017-07-01_08-28-09](https://user-images.githubusercontent.com/2099795/27759710-896f45fc-5e37-11e7-96a5-3796684870bb.png)

**Comment by yourhead** [comment]
Can you send me the stack in question. (The version that you had installed at the time of this screenshot).

Can you tell me if you're using your monitor in retina/HiDPI mode? From the screenshot it appears the answer is no -- but some screenshot utils auto-scale -- so could be either way.

**Comment by jrondorf** [comment]
It happened with different stacks, also foundry

**Comment by jrondorf** [comment]
That was MacBook Pro with retina on 1920*... I guess. Can have a deeper look later...

**Comment by yourhead** [comment]
never mind. i've already managed to isolate it.  thanks!

**Comment by yourhead** [comment]
that one time i documented the icon API as "image_large" in some places and "large_image" in others -- years later i'm still paying for that mistake.  😉 

hopefully should be an easy fix.

**Comment by yourhead** [comment]
fixed in beta 11
