### ISSUE TITLE
stacks that still use deprecated %repeat% API not updating correct in latest betas

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#725]
did i mention that repeat is deprecated

**Comment by yourhead** [comment]
typo. omg. that was sad.

**Comment by joeworkman** [comment]
Deprecated is a big word...

**Comment by yourhead** [comment]
i was going to fix this right away. i mean, i've already fixed it. but i think we need to make %repeat% suffer for at least 24 hours. it kind of deserves it.
