### ISSUE TITLE
Child stacks are not being added by -addInit=x

### ISSUE THREAD

**Issue by atavernor** [yourhead/s3#726]
Stacks that use `addInit=x` do not have any child stacks added when dropped on the page.

**Expected behavior**
Using  stacks 3.2.7

- Drop a Foundation Block Grid on to the page
- One block grid item child is added automatically - expected behavior with `-addInit=1`

**Regressive behavior**
Using stacks b15_4064

- Drop a Foundation Block Grid stack on to the page
- No Block grid item child stacks are added automatically.

**Comment by yourhead** [comment]
see also #728

**Comment by yourhead** [comment]
regression: broken when repairing the init sequence for repopulate. i suspect we haven't seen the last of what broke there. the entire init sequence needs refactor and unit test.

**Comment by yourhead** [comment]
fixed in beta 17
