### ISSUE TITLE
Missing stacks prevent access to their contents

### ISSUE THREAD

**Issue by atavernor** [yourhead/s3#727]
If a stack is no longer installed and thus displays the Missing Stack message and hatched background, its contents are no longer accessible.

It seems that users should be able to see and drag out their other stacks from within a missing stack without having to re-install it.

**Comment by yourhead** [comment]
yes -- good catch.

in the past, when i don't have any idea what to display -- i've treated the stack as a container -- which gives access to all child-content

**Comment by yourhead** [comment]
fixed in beta 17
