### ISSUE TITLE
No child stacks being populated with -addTypes

### ISSUE THREAD

**Issue by elixirgraphics** [yourhead/s3#728]
Had a user report a problem, which lead me to looking at `addTypes`. In the beta it seems that the `addInit` number is being ignored and no child stacks are being added to the parent when a new parent is placed on the page. 

An example of this would be if you start a new project file and add the Foundry Control Center stack and the Foundry Slider stack to the page. The child stacks are not being populated in the Slider stack.  This seems to be the case with any of the child stacks. All of the child stacks do have an `info.plist` file. If you want a project file for this, let me know and I'll send one over.

**Comment by joeworkman** [comment]
dup #726
