### ISSUE TITLE
User selectable text inside Edit Mode

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#751]
I have a few stacks now that generate a small code snippet for users to use on the page. It would be awesome if users were actually able to copy these to the clipboard. 

These snippets use data from the settings to dynamically create them. 

Maybe you could make `<code>` block selectable for that users could copy? Or possibly a button that could copy the resulting data to the clipboard.

**Comment by yourhead** [comment]
not going to happen. too difficult to both disallow most other interaction and also allow text selection.
