### ISSUE TITLE
warning: constant OpenSSL::Cipher::Cipher is deprecated

### ISSUE THREAD

**Issue by barchard** [yourhead/s3#753]
FYI, I received the following while running the generate keys command

```
./generate_keys.rb:33: warning: constant OpenSSL::Cipher::Cipher is deprecated
```

[this project](https://github.com/cvonkleist/encrypted_cookie/issues/12) had the same issue. It looks like they fixed it [here](https://github.com/evertrue/encrypted_cookie/commit/43bf6ee3765c6c2299ee739063d61766d14f4a98)

```
ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
```

**Comment by yourhead** [comment]
i'm aware of the deprecations of openssl -- i chose to use it anyway because it's sufficient for this work (we're not hiding military grade secrets here) -- just need enough security to dissuade would-be crackers to move on to a different target.

that said, i'll look into this.
