### ISSUE TITLE
Ability to Copy Text within edit mode

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#763]
It would be nice to have the ability to make text copiable inside Edit Mode. 

Example: Total CMS support text macros that allow users to integrate CMS data into any stack. I display these macros inside the stack in Edit Mode. However, users cannot copy these macros. Being able to copy them would be make it much easier for users.

**Comment by yourhead** [comment]
this is a duplicate of the other text-selection one that i just closed. so i'm closing this one too.
