### ISSUE TITLE
blank lines are being inserted into the end of stacks site css file

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#768]

**Comment by joeworkman** [comment]
It would be a welcome addition if all blank lines inside the CSS and JS file. Maybe even the HTML output could be trimmed.

**Comment by yourhead** [comment]
🙄

i huger for the day when the largest concern on my to-do list is a few dozen extraneous whitespace characters on the ends of files. until then i'm closing this bug. will reopen if nirvana arrives.
