### ISSUE TITLE
Stack versioning + older projects

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#782]
Many customers open an older project that was done years ago. By now most of the stacks used in the project have been updated many times. It can be a pain for the users to update these older projects again because so much has changed since they were originally completed. 

It would be great if there could be a supported solution for these older project files so that older versions of stacks could be loaded.

**Comment by yourhead** [comment]
I don't see any obvious practical way to achieving that. I mean, it's essentially re-inventing TimeMachine. You'd have to archive every version of every stack used in the site. To be thorough you'd probably want the version of Stacks and RW too.

I think the simplest solution would be a separate tool that could use git or similar to create archives.

How do you see this working from within RW?

**Comment by joeworkman** [comment]
I don't know to be honest. I just know that its an issue that many user have and wanted to throw it out these to see if anyone else had any ideas.

**Comment by yourhead** [comment]
I'd recommend TimeMachine on their addons folder. Anything else is going to be a half-assed solution. And they (should) already have that all set up.
