### ISSUE TITLE
Folder as a Library

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#795]
I now have a few stacks that ship with self contained web apps. (Example: Total CMS) Right now I add the folder that contains the web app as a site asset. These could contains 100s of files. When there are multiple stacks on a page that use the same site asset, it seems to publish it multiple times (my assumption could be wrong). 

If these were a library, then my assumption would be that it would only get published once. 

I could not really nail down how to debug if this was true. If I am wrong, feel free to close this issue.

**Comment by yourhead** [comment]
I think this is the bug that RW fixed in the release in late Nov early Dec.  In any case -- I suspect this is their bug.

I'm going to close this assuming it's the RW thing -- if not, please give some more concrete examples of how to reproduce or where to go hunting for this.
