### ISSUE TITLE
Built in columns stacks not clearing below.

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#801]
I came across this, granted, removing the "overflow:hidden" from a built in 2 columns stack with jQuery.

Currently removing "overflow:hidden" from a 2 column stack breaks the layout below.

But if I add this to my CSS, targeting all Yourhead columns stacks, to clear below the columns, all is well again....

div[class*="_columns_stack"]:after {
  content: "";
  display: table;
  clear: both;
  height: 0;
}

It would be better if this was built in.

**Comment by yourhead** [comment]
yes, hiding overflow is the same as clearing below. that's the expected behavior.
if you remove the hidden then you'll have to find another way to do the clearing.
