### ISSUE TITLE
Page Scoped detail settings do not work

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#812]
I am just testing the page scope of the detailed settings. It looks so much nicer now. But the detail setting does not work. It is not showing my detailed settings. If I take away the page scope, it works again. No rush. It’s a super minor detail right now.

**Comment by yourhead** [comment]
can you give me a little more context about what things you're talking about. "page scoped detail settings" seems like something i should recognize, but i'm drawing a blank.  what are these?

**Comment by joeworkman** [comment]
This is the issue with page scoped settings with enables not working. Closing...
