### ISSUE TITLE
dark mode - dark edit mode

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#825]
- dark backgrounds
- inverted text editing
- saturated color palette

**Comment by jrondorf** [comment]
Most probably the one or the other developer added custom colors for layouting the edit mode.

So we need a template like %[if dark_mode]% to distinguish and change our colors according to that.

**Comment by yourhead** [comment]
@jrondorf - it will be a simple CSS class that's added to the page, you can use CSS to reference it.
