### ISSUE TITLE
right clicking on selected link text causes immediate crash

### ISSUE THREAD

**Issue by atavernor** [yourhead/s3#829]
Any theme.

Add a  Text stack on the page.

Create a page link within the text using the Stacks link button as normal.

Drag select part of the link and part of the adjacent text (i.e. go over the end of the link - see image below)

<img width="274" alt="screen shot 2018-09-27 at 21 08 20" src="https://user-images.githubusercontent.com/8500380/46171798-8f9cc180-c299-11e8-8e98-8a49f3566505.png">

**Right clicking on the selected text causes immediate crash of RW.**
Related to  #809 ??

------
0   com.apple.CoreFoundation            0x00007fff2c4e32c3 __exceptionPreprocess + 147
1   libobjc.A.dylib                     0x00007fff53684c76 objc_exception_throw + 48
2   com.apple.CoreFoundation            0x00007fff2c5245e4 _CFThrowFormattedException + 202
3   com.apple.CoreFoundation            0x00007fff2c3e670c -[__NSDictionaryM setObject:forKey:] + 1020
4   com.apple.WebKitLegacy              0x00007fff3af5a39d __115+[WebImmediateActionController _dictionaryPopupInfoForRange:inFrame:withLookupOptions:indicatorOptions:transition:]_block_invoke + 173
5   com.apple.Foundation                0x00007fff2e586277 -[NSAttributedString enumerateAttributesInRange:options:usingBlock:] + 379
6   com.apple.WebKitLegacy              0x00007fff3af59edb +[WebImmediateActionController _dictionaryPopupInfoForRange:inFrame:withLookupOptions:indicatorOptions:transition:] + 923
7   com.apple.WebKitLegacy              0x00007fff3af5a662 -[WebImmediateActionController _animationControllerForText] + 162
8   com.apple.WebKitLegacy              0x00007fff3af5870e -[WebImmediateActionController _defaultAnimationController] + 814
9   com.apple.WebKitLegacy              0x00007fff3af588cd -[WebImmediateActionController _updateImmediateActionItem] + 45
10  com.apple.WebKitLegacy              0x00007fff3af57f83 -[WebImmediateActionController immediateActionRecognizerWillPrepare:] + 211
11  com.apple.AppKit                    0x00007fff2a450030 -[NSImmediateActionGestureRecognizer _didSendActions] + 312
12  com.apple.AppKit                    0x00007fff2a490d65 _NSGestureRecognizerSendActions + 570
13  com.apple.AppKit                    0x00007fff2a490a54 -[NSGestureRecognizer _updateGestureWithEvent:] + 2196
14  com.apple.AppKit                    0x00007fff2a4505ed -[NSImmediateActionGestureRecognizer mouseDown:] + 248
15  com.apple.AppKit                    0x00007fff2a331bce -[NSWindow(NSGestureRecognizer_Routing) _sendEventToGestureRecognizers:requireAcceptsFirstMouse:] + 2809
16  com.apple.AppKit                    0x00007fff2a32fd1e -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5812
17  com.apple.AppKit                    0x00007fff2a32c9c4 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2359
18  com.apple.AppKit                    0x00007fff2a32bc70 -[NSWindow(NSEventRouting) sendEvent:] + 497
19  com.apple.AppKit                    0x00007fff2a18d236 -[NSApplication(NSEvent) sendEvent:] + 2462
20  com.apple.AppKit                    0x00007fff299ed8b5 -[NSApplication run] + 812
21  com.apple.AppKit                    0x00007fff299bca72 NSApplicationMain + 804
22  libdyld.dylib                       0x00007fff5429e015 start + 1

**Comment by atavernor** [comment]
The problem is identical in RW7 and RW8

**Comment by yourhead** [comment]
Nice reporting. The selection (start at the first character of the selection and extend past) is very important.  Some other similar selections do not produce the crash.

However, there is no Stacks code in that crash report. And the same happens in a styled text page, so it's likely this is a RW bug.  I can file it with them if you like.
