### ISSUE TITLE
crash while publishing/exporting

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#832]
When exporting a project with:

- a partial
- that exists on an unloaded page
- that does not have the most up to date partial version

The partial version update will populate the new nodes, which will trigger a background edit-mode refresh, this triggers an initialization of the YHStacksPage object -- but with no views in-window.

This has worked fine for years, but seems to trigger a WebKit crash now -- this is with WebKit in Mojave in November 2018.

**Comment by yourhead** [comment]
A workaround is to avoid the edit-mode refresh trigger while publishing if the current nodeController is not yet in a window.

This may have other positive performance improvements at the cost of adding a property lookup to the refresh call.  Unmeasured but I suspect the overall impact on performance is minimal and positive.

**Comment by yourhead** [comment]
Bug fixed in 3.6.5 beta 1

**Comment by pbriesch** [comment]
I have this problem as well.
Where can I download 3.6.5 beta 1?

**Comment by yourhead** [comment]
All our betas are always available on the Stacks Slack channel. Go to http://slack.yourhead.com to get an invite to the channel.
